// Städte-Daten: {name_de, name_en, lon, lat, country}
const CITIES = {
  DE_BERLIN: {name_de:"Berlin", name_en:"Berlin", name_es:"Berlín", name_fr:"Berlin", lon:13.405, lat:52.52, country:"DE", difficulty:"easy"},
  DE_MUNICH: {name_de:"München", name_en:"Munich", name_es:"Múnich", name_fr:"Munich", lon:11.582, lat:48.137, country:"DE", difficulty:"easy"},
  DE_HAMBURG: {name_de:"Hamburg", name_en:"Hamburg", name_es:"Hamburgo", name_fr:"Hambourg", lon:10, lat:53.55, country:"DE", difficulty:"easy"},
  DE_COLOGNE: {name_de:"Köln", name_en:"Cologne", name_es:"Colonia", name_fr:"Cologne", lon:6.961, lat:50.938, country:"DE", difficulty:"medium"},
  DE_FRANKFURT: {name_de:"Frankfurt", name_en:"Frankfurt", name_es:"Fráncfort", name_fr:"Francfort", lon:8.68, lat:50.11, country:"DE", difficulty:"medium"},
  DE_STUTTGART: {name_de:"Stuttgart", name_en:"Stuttgart", name_es:"Stuttgart", name_fr:"Stuttgart", lon:9.11, lat:48.77, country:"DE", difficulty:"medium"},
  DE_DUSSELDORF: {name_de:"Düsseldorf", name_en:"Düsseldorf", name_es:"Dusseldorf", name_fr:"Düsseldorf", lon:6.778, lat:51.227, country:"DE", difficulty:"hard"},
  DE_DRESDEN: {name_de:"Dresden", name_en:"Dresden", name_es:"Dresde", name_fr:"Dresde", lon:13.733, lat:51.05, country:"DE", difficulty:"hard"},
  US_NYC: {name_de:"New York", name_en:"New York", name_es:"Nueva York", name_fr:"New York", lon:-74.006, lat:40.713, country:"US", difficulty:"easy"},
  US_LA: {name_de:"Los Angeles", name_en:"Los Angeles", name_es:"Los Ángeles", name_fr:"Los Angeles", lon:-118.243, lat:34.052, country:"US", difficulty:"easy"},
  US_CHICAGO: {name_de:"Chicago", name_en:"Chicago", name_es:"Chicago", name_fr:"Chicago", lon:-87.629, lat:41.878, country:"US", difficulty:"easy"},
  US_HOUSTON: {name_de:"Houston", name_en:"Houston", name_es:"Houston", name_fr:"Houston", lon:-95.369, lat:29.76, country:"US", difficulty:"medium"},
  US_PHOENIX: {name_de:"Phoenix", name_en:"Phoenix", name_es:"Fénix", name_fr:"Phoenix", lon:-112.074, lat:33.448, country:"US", difficulty:"medium"},
  US_MIAMI: {name_de:"Miami", name_en:"Miami", name_es:"Miami", name_fr:"Miami", lon:-80.194, lat:25.761, country:"US", difficulty:"medium"},
  US_DENVER: {name_de:"Denver", name_en:"Denver", name_es:"Denver", name_fr:"Denver", lon:-104.99, lat:39.739, country:"US", difficulty:"hard"},
  US_SEATTLE: {name_de:"Seattle", name_en:"Seattle", name_es:"Seattle", name_fr:"Seattle", lon:-122.332, lat:47.606, country:"US", difficulty:"hard"},
  FR_PARIS: {name_de:"Paris", name_en:"Paris", name_es:"París", name_fr:"Paris", lon:2.352, lat:48.856, country:"FR", difficulty:"easy"},
  FR_MARSEILLE: {name_de:"Marseille", name_en:"Marseille", name_es:"Marsella", name_fr:"Marseille", lon:5.397, lat:43.296, country:"FR", difficulty:"easy"},
  FR_LYON: {name_de:"Lyon", name_en:"Lyon", name_es:"Lyon", name_fr:"Lyon", lon:4.836, lat:45.764, country:"FR", difficulty:"easy"},
  FR_TOULOUSE: {name_de:"Toulouse", name_en:"Toulouse", name_es:"Toulouse", name_fr:"Toulouse", lon:1.443, lat:43.604, country:"FR", difficulty:"medium"},
  FR_NICE: {name_de:"Nizza", name_en:"Nice", name_es:"Niza", name_fr:"Nice", lon:7.262, lat:43.71, country:"FR", difficulty:"medium"},
  FR_NANTES: {name_de:"Nantes", name_en:"Nantes", name_es:"Nantes", name_fr:"Nantes", lon:-1.552, lat:47.218, country:"FR", difficulty:"medium"},
  FR_STRASBOURG: {name_de:"Straßburg", name_en:"Strasbourg", name_es:"Estrasburgo", name_fr:"Strasbourg", lon:7.753, lat:48.573, country:"FR", difficulty:"hard"},
  FR_BORDEAUX: {name_de:"Bordeaux", name_en:"Bordeaux", name_es:"Burdeos", name_fr:"Bordeaux", lon:-0.576, lat:44.841, country:"FR", difficulty:"hard"}
};

// Länder-Gruppen für Quiz-Modi
const CITY_COUNTRIES = {
  DE: {label_de:'Deutschland', label_en:'Germany', cities:Object.entries(CITIES).filter(([k,v])=>v.country==='DE').map(([k,v])=>v)},
  US: {label_de:'USA', label_en:'USA', cities:Object.entries(CITIES).filter(([k,v])=>v.country==='US').map(([k,v])=>v)},
  FR: {label_de:'Frankreich', label_en:'France', cities:Object.entries(CITIES).filter(([k,v])=>v.country==='FR').map(([k,v])=>v)}
};

function getCitiesByDifficulty(country, difficulty) {
  if(!CITY_COUNTRIES[country]) return [];
  return CITY_COUNTRIES[country].cities.filter(c=>c.difficulty===difficulty);
}

function getAllCitiesByDifficulty(difficulty) {
  return Object.values(CITIES).filter(c=>c.difficulty===difficulty);
}

// Drop-A-Pin: große Städte-Datenbank. cont = Kontinent (EU/AF/AS/NA/SA/OC),
// country = DE/FR/US für die Länder-spezifischen Quizze (diese Städte sind zugleich Teil ihres Kontinents).
const PIN_CITIES = [
  {name_de:"London", name_en:"London", name_es:"Londres", name_fr:"Londres", lon:-0.13, lat:51.51, cont:"EU"},
  {name_de:"Edinburgh", name_en:"Edinburgh", name_es:"Edimburgo", name_fr:"Édimbourg", lon:-3.19, lat:55.95, cont:"EU"},
  {name_de:"Manchester", name_en:"Manchester", name_es:"Manchester", name_fr:"Manchester", lon:-2.24, lat:53.48, cont:"EU"},
  {name_de:"Dublin", name_en:"Dublin", name_es:"Dublín", name_fr:"Dublin", lon:-6.26, lat:53.35, cont:"EU"},
  {name_de:"Madrid", name_en:"Madrid", name_es:"Madrid", name_fr:"Madrid", lon:-3.7, lat:40.42, cont:"EU"},
  {name_de:"Barcelona", name_en:"Barcelona", name_es:"Barcelona", name_fr:"Barcelona", lon:2.17, lat:41.39, cont:"EU"},
  {name_de:"Sevilla", name_en:"Seville", name_es:"Sevilla", name_fr:"Séville", lon:-5.98, lat:37.39, cont:"EU"},
  {name_de:"Lissabon", name_en:"Lisbon", name_es:"Lisboa", name_fr:"Lisbonne", lon:-9.14, lat:38.72, cont:"EU"},
  {name_de:"Porto", name_en:"Porto", name_es:"Porto", name_fr:"Porto", lon:-8.61, lat:41.15, cont:"EU"},
  {name_de:"Rom", name_en:"Rome", name_es:"Roma", name_fr:"Rome", lon:12.5, lat:41.9, cont:"EU"},
  {name_de:"Mailand", name_en:"Milan", name_es:"Milán", name_fr:"Milan", lon:9.19, lat:45.46, cont:"EU"},
  {name_de:"Neapel", name_en:"Naples", name_es:"Nápoles", name_fr:"Naples", lon:14.27, lat:40.85, cont:"EU"},
  {name_de:"Venedig", name_en:"Venice", name_es:"Venecia", name_fr:"Venise", lon:12.34, lat:45.44, cont:"EU"},
  {name_de:"Amsterdam", name_en:"Amsterdam", name_es:"Amsterdam", name_fr:"Amsterdam", lon:4.9, lat:52.37, cont:"EU"},
  {name_de:"Rotterdam", name_en:"Rotterdam", name_es:"Rotterdam", name_fr:"Rotterdam", lon:4.48, lat:51.92, cont:"EU"},
  {name_de:"Brüssel", name_en:"Brussels", name_es:"Bruselas", name_fr:"Bruxelles", lon:4.35, lat:50.85, cont:"EU"},
  {name_de:"Wien", name_en:"Vienna", name_es:"Viena", name_fr:"Vienne", lon:16.37, lat:48.21, cont:"EU"},
  {name_de:"Zürich", name_en:"Zurich", name_es:"Zúrich", name_fr:"Zurich", lon:8.54, lat:47.37, cont:"EU"},
  {name_de:"Genf", name_en:"Geneva", name_es:"Ginebra", name_fr:"Genève", lon:6.14, lat:46.2, cont:"EU"},
  {name_de:"Bern", name_en:"Bern", name_es:"Bern", name_fr:"Bern", lon:7.45, lat:46.95, cont:"EU"},
  {name_de:"Warschau", name_en:"Warsaw", name_es:"Varsovia", name_fr:"Varsovie", lon:21.01, lat:52.23, cont:"EU"},
  {name_de:"Krakau", name_en:"Krakow", name_es:"Cracovia", name_fr:"Cracovie", lon:19.94, lat:50.06, cont:"EU"},
  {name_de:"Prag", name_en:"Prague", name_es:"Praga", name_fr:"Prague", lon:14.44, lat:50.08, cont:"EU"},
  {name_de:"Budapest", name_en:"Budapest", name_es:"Budapest", name_fr:"Budapest", lon:19.04, lat:47.5, cont:"EU"},
  {name_de:"Bratislava", name_en:"Bratislava", name_es:"Bratislava", name_fr:"Bratislava", lon:17.11, lat:48.15, cont:"EU"},
  {name_de:"Stockholm", name_en:"Stockholm", name_es:"Stockholm", name_fr:"Stockholm", lon:18.07, lat:59.33, cont:"EU"},
  {name_de:"Göteborg", name_en:"Gothenburg", name_es:"Gothenburg", name_fr:"Gothenburg", lon:11.97, lat:57.71, cont:"EU"},
  {name_de:"Oslo", name_en:"Oslo", name_es:"Oslo", name_fr:"Oslo", lon:10.75, lat:59.91, cont:"EU"},
  {name_de:"Kopenhagen", name_en:"Copenhagen", name_es:"Copenhagen", name_fr:"Copenhagen", lon:12.57, lat:55.68, cont:"EU"},
  {name_de:"Helsinki", name_en:"Helsinki", name_es:"Helsinki", name_fr:"Helsinki", lon:24.94, lat:60.17, cont:"EU"},
  {name_de:"Reykjavík", name_en:"Reykjavik", name_es:"Reykjavik", name_fr:"Reykjavik", lon:-21.83, lat:64.13, cont:"EU"},
  {name_de:"Athen", name_en:"Athens", name_es:"Atenas", name_fr:"Athènes", lon:23.73, lat:37.98, cont:"EU"},
  {name_de:"Thessaloniki", name_en:"Thessaloniki", name_es:"Thessaloniki", name_fr:"Thessaloniki", lon:22.94, lat:40.64, cont:"EU"},
  {name_de:"Bukarest", name_en:"Bucharest", name_es:"Bucarest", name_fr:"Bucarest", lon:26.1, lat:44.43, cont:"EU"},
  {name_de:"Sofia", name_en:"Sofia", name_es:"Sofia", name_fr:"Sofia", lon:23.32, lat:42.7, cont:"EU"},
  {name_de:"Belgrad", name_en:"Belgrade", name_es:"Belgrado", name_fr:"Belgrade", lon:20.46, lat:44.79, cont:"EU"},
  {name_de:"Zagreb", name_en:"Zagreb", name_es:"Zagreb", name_fr:"Zagreb", lon:15.98, lat:45.81, cont:"EU"},
  {name_de:"Ljubljana", name_en:"Ljubljana", name_es:"Ljubljana", name_fr:"Ljubljana", lon:14.51, lat:46.06, cont:"EU"},
  {name_de:"Tallinn", name_en:"Tallinn", name_es:"Tallinn", name_fr:"Tallinn", lon:24.75, lat:59.44, cont:"EU"},
  {name_de:"Riga", name_en:"Riga", name_es:"Riga", name_fr:"Riga", lon:24.11, lat:56.95, cont:"EU"},
  {name_de:"Vilnius", name_en:"Vilnius", name_es:"Vilnius", name_fr:"Vilnius", lon:25.28, lat:54.69, cont:"EU"},
  {name_de:"Kiew", name_en:"Kyiv", name_es:"Kiev", name_fr:"Kiev", lon:30.52, lat:50.45, cont:"EU"},
  {name_de:"Moskau", name_en:"Moscow", name_es:"Moscú", name_fr:"Moscou", lon:37.62, lat:55.76, cont:"EU"},
  {name_de:"Sankt Petersburg", name_en:"St. Petersburg", name_es:"San Petersburgo", name_fr:"Saint-Pétersbourg", lon:30.34, lat:59.93, cont:"EU"},
  {name_de:"Berlin", name_en:"Berlin", name_es:"Berlin", name_fr:"Berlin", lon:13.4, lat:52.52, cont:"EU", country:"DE"},
  {name_de:"Hamburg", name_en:"Hamburg", name_es:"Hamburg", name_fr:"Hamburg", lon:10, lat:53.55, cont:"EU", country:"DE"},
  {name_de:"München", name_en:"Munich", name_es:"Múnich", name_fr:"Munich", lon:11.58, lat:48.14, cont:"EU", country:"DE"},
  {name_de:"Köln", name_en:"Cologne", name_es:"Colonia", name_fr:"Cologne", lon:6.96, lat:50.94, cont:"EU", country:"DE"},
  {name_de:"Frankfurt", name_en:"Frankfurt", name_es:"Frankfurt", name_fr:"Frankfurt", lon:8.68, lat:50.11, cont:"EU", country:"DE"},
  {name_de:"Stuttgart", name_en:"Stuttgart", name_es:"Stuttgart", name_fr:"Stuttgart", lon:9.18, lat:48.78, cont:"EU", country:"DE"},
  {name_de:"Düsseldorf", name_en:"Düsseldorf", name_es:"Düsseldorf", name_fr:"Düsseldorf", lon:6.78, lat:51.23, cont:"EU", country:"DE"},
  {name_de:"Dortmund", name_en:"Dortmund", name_es:"Dortmund", name_fr:"Dortmund", lon:7.47, lat:51.51, cont:"EU", country:"DE"},
  {name_de:"Essen", name_en:"Essen", name_es:"Essen", name_fr:"Essen", lon:7.01, lat:51.46, cont:"EU", country:"DE"},
  {name_de:"Leipzig", name_en:"Leipzig", name_es:"Leipzig", name_fr:"Leipzig", lon:12.37, lat:51.34, cont:"EU", country:"DE"},
  {name_de:"Dresden", name_en:"Dresden", name_es:"Dresden", name_fr:"Dresden", lon:13.74, lat:51.05, cont:"EU", country:"DE"},
  {name_de:"Hannover", name_en:"Hanover", name_es:"Hanover", name_fr:"Hanover", lon:9.73, lat:52.37, cont:"EU", country:"DE"},
  {name_de:"Nürnberg", name_en:"Nuremberg", name_es:"Núremberg", name_fr:"Nuremberg", lon:11.08, lat:49.45, cont:"EU", country:"DE"},
  {name_de:"Bremen", name_en:"Bremen", name_es:"Bremen", name_fr:"Bremen", lon:8.8, lat:53.08, cont:"EU", country:"DE"},
  {name_de:"Duisburg", name_en:"Duisburg", name_es:"Duisburg", name_fr:"Duisburg", lon:6.76, lat:51.43, cont:"EU", country:"DE"},
  {name_de:"Bonn", name_en:"Bonn", name_es:"Bonn", name_fr:"Bonn", lon:7.1, lat:50.74, cont:"EU", country:"DE"},
  {name_de:"Münster", name_en:"Münster", name_es:"Münster", name_fr:"Münster", lon:7.63, lat:51.96, cont:"EU", country:"DE"},
  {name_de:"Karlsruhe", name_en:"Karlsruhe", name_es:"Karlsruhe", name_fr:"Karlsruhe", lon:8.4, lat:49.01, cont:"EU", country:"DE"},
  {name_de:"Mannheim", name_en:"Mannheim", name_es:"Mannheim", name_fr:"Mannheim", lon:8.47, lat:49.49, cont:"EU", country:"DE"},
  {name_de:"Augsburg", name_en:"Augsburg", name_es:"Augsburg", name_fr:"Augsburg", lon:10.9, lat:48.37, cont:"EU", country:"DE"},
  {name_de:"Wiesbaden", name_en:"Wiesbaden", name_es:"Wiesbaden", name_fr:"Wiesbaden", lon:8.24, lat:50.08, cont:"EU", country:"DE"},
  {name_de:"Kiel", name_en:"Kiel", name_es:"Kiel", name_fr:"Kiel", lon:10.14, lat:54.32, cont:"EU", country:"DE"},
  {name_de:"Freiburg", name_en:"Freiburg", name_es:"Freiburg", name_fr:"Freiburg", lon:7.85, lat:47.99, cont:"EU", country:"DE"},
  {name_de:"Rostock", name_en:"Rostock", name_es:"Rostock", name_fr:"Rostock", lon:12.14, lat:54.09, cont:"EU", country:"DE"},
  {name_de:"Saarbrücken", name_en:"Saarbrücken", name_es:"Saarbrücken", name_fr:"Saarbrücken", lon:6.99, lat:49.23, cont:"EU", country:"DE"},
  {name_de:"Paris", name_en:"Paris", name_es:"Paris", name_fr:"Paris", lon:2.35, lat:48.86, cont:"EU", country:"FR"},
  {name_de:"Marseille", name_en:"Marseille", name_es:"Marseille", name_fr:"Marseille", lon:5.37, lat:43.3, cont:"EU", country:"FR"},
  {name_de:"Lyon", name_en:"Lyon", name_es:"Lyon", name_fr:"Lyon", lon:4.84, lat:45.76, cont:"EU", country:"FR"},
  {name_de:"Toulouse", name_en:"Toulouse", name_es:"Toulouse", name_fr:"Toulouse", lon:1.44, lat:43.6, cont:"EU", country:"FR"},
  {name_de:"Nizza", name_en:"Nice", name_es:"Niza", name_fr:"Nice", lon:7.27, lat:43.7, cont:"EU", country:"FR"},
  {name_de:"Nantes", name_en:"Nantes", name_es:"Nantes", name_fr:"Nantes", lon:-1.55, lat:47.22, cont:"EU", country:"FR"},
  {name_de:"Straßburg", name_en:"Strasbourg", name_es:"Estrasburgo", name_fr:"Strasbourg", lon:7.75, lat:48.57, cont:"EU", country:"FR"},
  {name_de:"Bordeaux", name_en:"Bordeaux", name_es:"Bordeaux", name_fr:"Bordeaux", lon:-0.58, lat:44.84, cont:"EU", country:"FR"},
  {name_de:"Lille", name_en:"Lille", name_es:"Lille", name_fr:"Lille", lon:3.06, lat:50.63, cont:"EU", country:"FR"},
  {name_de:"Montpellier", name_en:"Montpellier", name_es:"Montpellier", name_fr:"Montpellier", lon:3.88, lat:43.61, cont:"EU", country:"FR"},
  {name_de:"Rennes", name_en:"Rennes", name_es:"Rennes", name_fr:"Rennes", lon:-1.68, lat:48.11, cont:"EU", country:"FR"},
  {name_de:"Reims", name_en:"Reims", name_es:"Reims", name_fr:"Reims", lon:4.03, lat:49.26, cont:"EU", country:"FR"},
  {name_de:"Le Havre", name_en:"Le Havre", name_es:"Le Havre", name_fr:"Le Havre", lon:0.11, lat:49.49, cont:"EU", country:"FR"},
  {name_de:"Toulon", name_en:"Toulon", name_es:"Toulon", name_fr:"Toulon", lon:5.93, lat:43.12, cont:"EU", country:"FR"},
  {name_de:"Grenoble", name_en:"Grenoble", name_es:"Grenoble", name_fr:"Grenoble", lon:5.72, lat:45.19, cont:"EU", country:"FR"},
  {name_de:"Dijon", name_en:"Dijon", name_es:"Dijon", name_fr:"Dijon", lon:5.04, lat:47.32, cont:"EU", country:"FR"},
  {name_de:"Brest", name_en:"Brest", name_es:"Brest", name_fr:"Brest", lon:-4.49, lat:48.39, cont:"EU", country:"FR"},
  {name_de:"Nancy", name_en:"Nancy", name_es:"Nancy", name_fr:"Nancy", lon:6.18, lat:48.69, cont:"EU", country:"FR"},
  {name_de:"Tokio", name_en:"Tokyo", name_es:"Tokio", name_fr:"Tokyo", lon:139.69, lat:35.69, cont:"AS"},
  {name_de:"Osaka", name_en:"Osaka", name_es:"Osaka", name_fr:"Osaka", lon:135.5, lat:34.69, cont:"AS"},
  {name_de:"Peking", name_en:"Beijing", name_es:"Pekín", name_fr:"Pékin", lon:116.41, lat:39.9, cont:"AS"},
  {name_de:"Shanghai", name_en:"Shanghai", name_es:"Shanghai", name_fr:"Shanghai", lon:121.47, lat:31.23, cont:"AS"},
  {name_de:"Hongkong", name_en:"Hong Kong", name_es:"Hong Kong", name_fr:"Hong Kong", lon:114.17, lat:22.32, cont:"AS"},
  {name_de:"Guangzhou", name_en:"Guangzhou", name_es:"Guangzhou", name_fr:"Guangzhou", lon:113.26, lat:23.13, cont:"AS"},
  {name_de:"Seoul", name_en:"Seoul", name_es:"Seoul", name_fr:"Seoul", lon:126.98, lat:37.57, cont:"AS"},
  {name_de:"Busan", name_en:"Busan", name_es:"Busan", name_fr:"Busan", lon:129.08, lat:35.18, cont:"AS"},
  {name_de:"Neu-Delhi", name_en:"New Delhi", name_es:"Nueva Delhi", name_fr:"New Delhi", lon:77.21, lat:28.61, cont:"AS"},
  {name_de:"Mumbai", name_en:"Mumbai", name_es:"Mumbai", name_fr:"Mumbai", lon:72.88, lat:19.08, cont:"AS"},
  {name_de:"Bangalore", name_en:"Bangalore", name_es:"Bangalore", name_fr:"Bangalore", lon:77.59, lat:12.97, cont:"AS"},
  {name_de:"Kolkata", name_en:"Kolkata", name_es:"Kolkata", name_fr:"Kolkata", lon:88.36, lat:22.57, cont:"AS"},
  {name_de:"Chennai", name_en:"Chennai", name_es:"Chennai", name_fr:"Chennai", lon:80.27, lat:13.08, cont:"AS"},
  {name_de:"Bangkok", name_en:"Bangkok", name_es:"Bangkok", name_fr:"Bangkok", lon:100.5, lat:13.76, cont:"AS"},
  {name_de:"Jakarta", name_en:"Jakarta", name_es:"Jakarta", name_fr:"Jakarta", lon:106.85, lat:-6.21, cont:"AS"},
  {name_de:"Singapur", name_en:"Singapore", name_es:"Singapur", name_fr:"Singapour", lon:103.82, lat:1.35, cont:"AS"},
  {name_de:"Kuala Lumpur", name_en:"Kuala Lumpur", name_es:"Kuala Lumpur", name_fr:"Kuala Lumpur", lon:101.69, lat:3.14, cont:"AS"},
  {name_de:"Manila", name_en:"Manila", name_es:"Manila", name_fr:"Manila", lon:120.98, lat:14.6, cont:"AS"},
  {name_de:"Hanoi", name_en:"Hanoi", name_es:"Hanoi", name_fr:"Hanoi", lon:105.83, lat:21.03, cont:"AS"},
  {name_de:"Ho-Chi-Minh-Stadt", name_en:"Ho Chi Minh City", name_es:"Ciudad Ho Chi Minh", name_fr:"Hô Chi Minh-Ville", lon:106.66, lat:10.82, cont:"AS"},
  {name_de:"Taipeh", name_en:"Taipei", name_es:"Taipéi", name_fr:"Taipei", lon:121.56, lat:25.03, cont:"AS"},
  {name_de:"Dubai", name_en:"Dubai", name_es:"Dubai", name_fr:"Dubai", lon:55.27, lat:25.2, cont:"AS"},
  {name_de:"Riad", name_en:"Riyadh", name_es:"Riad", name_fr:"Riyad", lon:46.72, lat:24.71, cont:"AS"},
  {name_de:"Teheran", name_en:"Tehran", name_es:"Teherán", name_fr:"Téhéran", lon:51.39, lat:35.69, cont:"AS"},
  {name_de:"Bagdad", name_en:"Baghdad", name_es:"Bagdad", name_fr:"Bagdad", lon:44.36, lat:33.31, cont:"AS"},
  {name_de:"Jerusalem", name_en:"Jerusalem", name_es:"Jerusalén", name_fr:"Jérusalem", lon:35.21, lat:31.77, cont:"AS"},
  {name_de:"Istanbul", name_en:"Istanbul", name_es:"Istanbul", name_fr:"Istanbul", lon:28.98, lat:41.01, cont:"AS"},
  {name_de:"Ankara", name_en:"Ankara", name_es:"Ankara", name_fr:"Ankara", lon:32.85, lat:39.93, cont:"AS"},
  {name_de:"Karachi", name_en:"Karachi", name_es:"Karachi", name_fr:"Karachi", lon:67.01, lat:24.86, cont:"AS"},
  {name_de:"Lahore", name_en:"Lahore", name_es:"Lahore", name_fr:"Lahore", lon:74.34, lat:31.55, cont:"AS"},
  {name_de:"Dhaka", name_en:"Dhaka", name_es:"Dhaka", name_fr:"Dhaka", lon:90.41, lat:23.81, cont:"AS"},
  {name_de:"Almaty", name_en:"Almaty", name_es:"Almaty", name_fr:"Almaty", lon:76.95, lat:43.24, cont:"AS"},
  {name_de:"Taschkent", name_en:"Tashkent", name_es:"Taskent", name_fr:"Tachkent", lon:69.24, lat:41.3, cont:"AS"},
  {name_de:"Colombo", name_en:"Colombo", name_es:"Colombo", name_fr:"Colombo", lon:79.86, lat:6.93, cont:"AS"},
  {name_de:"Kathmandu", name_en:"Kathmandu", name_es:"Katmandú", name_fr:"Katmandou", lon:85.32, lat:27.7, cont:"AS"},
  {name_de:"Kairo", name_en:"Cairo", name_es:"El Cairo", name_fr:"Le Caire", lon:31.24, lat:30.04, cont:"AF"},
  {name_de:"Alexandria", name_en:"Alexandria", name_es:"Alexandria", name_fr:"Alexandria", lon:29.92, lat:31.2, cont:"AF"},
  {name_de:"Lagos", name_en:"Lagos", name_es:"Lagos", name_fr:"Lagos", lon:3.38, lat:6.52, cont:"AF"},
  {name_de:"Abuja", name_en:"Abuja", name_es:"Abuja", name_fr:"Abuja", lon:7.49, lat:9.06, cont:"AF"},
  {name_de:"Nairobi", name_en:"Nairobi", name_es:"Nairobi", name_fr:"Nairobi", lon:36.82, lat:-1.29, cont:"AF"},
  {name_de:"Kapstadt", name_en:"Cape Town", name_es:"Ciudad del Cabo", name_fr:"Le Cap", lon:18.42, lat:-33.92, cont:"AF"},
  {name_de:"Johannesburg", name_en:"Johannesburg", name_es:"Johannesburg", name_fr:"Johannesburg", lon:28.05, lat:-26.2, cont:"AF"},
  {name_de:"Durban", name_en:"Durban", name_es:"Durban", name_fr:"Durban", lon:31.02, lat:-29.86, cont:"AF"},
  {name_de:"Casablanca", name_en:"Casablanca", name_es:"Casablanca", name_fr:"Casablanca", lon:-7.59, lat:33.57, cont:"AF"},
  {name_de:"Marrakesch", name_en:"Marrakesh", name_es:"Marrakech", name_fr:"Marrakech", lon:-7.98, lat:31.63, cont:"AF"},
  {name_de:"Tunis", name_en:"Tunis", name_es:"Túnez", name_fr:"Tunis", lon:10.18, lat:36.81, cont:"AF"},
  {name_de:"Algier", name_en:"Algiers", name_es:"Argel", name_fr:"Alger", lon:3.06, lat:36.75, cont:"AF"},
  {name_de:"Accra", name_en:"Accra", name_es:"Accra", name_fr:"Accra", lon:-0.19, lat:5.6, cont:"AF"},
  {name_de:"Abidjan", name_en:"Abidjan", name_es:"Abidjan", name_fr:"Abidjan", lon:-4.02, lat:5.36, cont:"AF"},
  {name_de:"Dakar", name_en:"Dakar", name_es:"Dakar", name_fr:"Dakar", lon:-17.45, lat:14.69, cont:"AF"},
  {name_de:"Addis Abeba", name_en:"Addis Ababa", name_es:"Adís Abeba", name_fr:"Addis-Abeba", lon:38.76, lat:9.03, cont:"AF"},
  {name_de:"Daressalam", name_en:"Dar es Salaam", name_es:"Dar es Salaam", name_fr:"Dar es-Salaam", lon:39.28, lat:-6.79, cont:"AF"},
  {name_de:"Khartum", name_en:"Khartoum", name_es:"Jartum", name_fr:"Khartoum", lon:32.53, lat:15.5, cont:"AF"},
  {name_de:"Kinshasa", name_en:"Kinshasa", name_es:"Kinshasa", name_fr:"Kinshasa", lon:15.31, lat:-4.32, cont:"AF"},
  {name_de:"Luanda", name_en:"Luanda", name_es:"Luanda", name_fr:"Luanda", lon:13.23, lat:-8.84, cont:"AF"},
  {name_de:"Harare", name_en:"Harare", name_es:"Harare", name_fr:"Harare", lon:31.05, lat:-17.83, cont:"AF"},
  {name_de:"Kampala", name_en:"Kampala", name_es:"Kampala", name_fr:"Kampala", lon:32.58, lat:0.35, cont:"AF"},
  {name_de:"Tripolis", name_en:"Tripoli", name_es:"Trípoli", name_fr:"Tripoli", lon:13.19, lat:32.89, cont:"AF"},
  {name_de:"Windhoek", name_en:"Windhoek", name_es:"Windhoek", name_fr:"Windhoek", lon:17.08, lat:-22.56, cont:"AF"},
  {name_de:"Maputo", name_en:"Maputo", name_es:"Maputo", name_fr:"Maputo", lon:32.57, lat:-25.97, cont:"AF"},
  {name_de:"Mexiko-Stadt", name_en:"Mexico City", name_es:"Ciudad de México", name_fr:"Mexico", lon:-99.13, lat:19.43, cont:"NA"},
  {name_de:"Guadalajara", name_en:"Guadalajara", name_es:"Guadalajara", name_fr:"Guadalajara", lon:-103.35, lat:20.66, cont:"NA"},
  {name_de:"Monterrey", name_en:"Monterrey", name_es:"Monterrey", name_fr:"Monterrey", lon:-100.32, lat:25.69, cont:"NA"},
  {name_de:"Toronto", name_en:"Toronto", name_es:"Toronto", name_fr:"Toronto", lon:-79.38, lat:43.65, cont:"NA"},
  {name_de:"Montreal", name_en:"Montreal", name_es:"Montreal", name_fr:"Montreal", lon:-73.57, lat:45.5, cont:"NA"},
  {name_de:"Vancouver", name_en:"Vancouver", name_es:"Vancouver", name_fr:"Vancouver", lon:-123.12, lat:49.28, cont:"NA"},
  {name_de:"Ottawa", name_en:"Ottawa", name_es:"Ottawa", name_fr:"Ottawa", lon:-75.7, lat:45.42, cont:"NA"},
  {name_de:"Calgary", name_en:"Calgary", name_es:"Calgary", name_fr:"Calgary", lon:-114.07, lat:51.05, cont:"NA"},
  {name_de:"Havanna", name_en:"Havana", name_es:"La Habana", name_fr:"La Havane", lon:-82.38, lat:23.11, cont:"NA"},
  {name_de:"Guatemala-Stadt", name_en:"Guatemala City", name_es:"Ciudad de Guatemala", name_fr:"Guatemala", lon:-90.51, lat:14.63, cont:"NA"},
  {name_de:"Panama-Stadt", name_en:"Panama City", name_es:"Ciudad de Panamá", name_fr:"Panama", lon:-79.52, lat:8.98, cont:"NA"},
  {name_de:"San José", name_en:"San José", name_es:"San José", name_fr:"San José", lon:-84.09, lat:9.93, cont:"NA"},
  {name_de:"Kingston", name_en:"Kingston", name_es:"Kingston", name_fr:"Kingston", lon:-76.79, lat:17.97, cont:"NA"},
  {name_de:"Santo Domingo", name_en:"Santo Domingo", name_es:"Santo Domingo", name_fr:"Santo Domingo", lon:-69.93, lat:18.49, cont:"NA"},
  {name_de:"New York", name_en:"New York", name_es:"Nueva York", name_fr:"New York", lon:-74.01, lat:40.71, cont:"NA", country:"US"},
  {name_de:"Los Angeles", name_en:"Los Angeles", name_es:"Los Ángeles", name_fr:"Los Angeles", lon:-118.24, lat:34.05, cont:"NA", country:"US"},
  {name_de:"Chicago", name_en:"Chicago", name_es:"Chicago", name_fr:"Chicago", lon:-87.63, lat:41.88, cont:"NA", country:"US"},
  {name_de:"Houston", name_en:"Houston", name_es:"Houston", name_fr:"Houston", lon:-95.37, lat:29.76, cont:"NA", country:"US"},
  {name_de:"Phoenix", name_en:"Phoenix", name_es:"Phoenix", name_fr:"Phoenix", lon:-112.07, lat:33.45, cont:"NA", country:"US"},
  {name_de:"Philadelphia", name_en:"Philadelphia", name_es:"Philadelphia", name_fr:"Philadelphia", lon:-75.17, lat:39.95, cont:"NA", country:"US"},
  {name_de:"San Antonio", name_en:"San Antonio", name_es:"San Antonio", name_fr:"San Antonio", lon:-98.49, lat:29.42, cont:"NA", country:"US"},
  {name_de:"San Diego", name_en:"San Diego", name_es:"San Diego", name_fr:"San Diego", lon:-117.16, lat:32.72, cont:"NA", country:"US"},
  {name_de:"Dallas", name_en:"Dallas", name_es:"Dallas", name_fr:"Dallas", lon:-96.8, lat:32.78, cont:"NA", country:"US"},
  {name_de:"Austin", name_en:"Austin", name_es:"Austin", name_fr:"Austin", lon:-97.74, lat:30.27, cont:"NA", country:"US"},
  {name_de:"San Francisco", name_en:"San Francisco", name_es:"San Francisco", name_fr:"San Francisco", lon:-122.42, lat:37.77, cont:"NA", country:"US"},
  {name_de:"Seattle", name_en:"Seattle", name_es:"Seattle", name_fr:"Seattle", lon:-122.33, lat:47.61, cont:"NA", country:"US"},
  {name_de:"Denver", name_en:"Denver", name_es:"Denver", name_fr:"Denver", lon:-104.99, lat:39.74, cont:"NA", country:"US"},
  {name_de:"Washington", name_en:"Washington D.C.", name_es:"Washington D. C.", name_fr:"Washington", lon:-77.04, lat:38.91, cont:"NA", country:"US"},
  {name_de:"Boston", name_en:"Boston", name_es:"Boston", name_fr:"Boston", lon:-71.06, lat:42.36, cont:"NA", country:"US"},
  {name_de:"Miami", name_en:"Miami", name_es:"Miami", name_fr:"Miami", lon:-80.19, lat:25.76, cont:"NA", country:"US"},
  {name_de:"Atlanta", name_en:"Atlanta", name_es:"Atlanta", name_fr:"Atlanta", lon:-84.39, lat:33.75, cont:"NA", country:"US"},
  {name_de:"Las Vegas", name_en:"Las Vegas", name_es:"Las Vegas", name_fr:"Las Vegas", lon:-115.14, lat:36.17, cont:"NA", country:"US"},
  {name_de:"Detroit", name_en:"Detroit", name_es:"Detroit", name_fr:"Detroit", lon:-83.05, lat:42.33, cont:"NA", country:"US"},
  {name_de:"Minneapolis", name_en:"Minneapolis", name_es:"Minneapolis", name_fr:"Minneapolis", lon:-93.27, lat:44.98, cont:"NA", country:"US"},
  {name_de:"New Orleans", name_en:"New Orleans", name_es:"Nueva Orleans", name_fr:"La Nouvelle-Orléans", lon:-90.07, lat:29.95, cont:"NA", country:"US"},
  {name_de:"Portland", name_en:"Portland", name_es:"Portland", name_fr:"Portland", lon:-122.68, lat:45.52, cont:"NA", country:"US"},
  {name_de:"Salt Lake City", name_en:"Salt Lake City", name_es:"Salt Lake City", name_fr:"Salt Lake City", lon:-111.89, lat:40.76, cont:"NA", country:"US"},
  {name_de:"Kansas City", name_en:"Kansas City", name_es:"Kansas City", name_fr:"Kansas City", lon:-94.58, lat:39.1, cont:"NA", country:"US"},
  {name_de:"St. Louis", name_en:"St. Louis", name_es:"St. Louis", name_fr:"St. Louis", lon:-90.2, lat:38.63, cont:"NA", country:"US"},
  {name_de:"Honolulu", name_en:"Honolulu", name_es:"Honolulu", name_fr:"Honolulu", lon:-157.86, lat:21.31, cont:"NA", country:"US"},
  {name_de:"São Paulo", name_en:"São Paulo", name_es:"São Paulo", name_fr:"São Paulo", lon:-46.63, lat:-23.55, cont:"SA"},
  {name_de:"Rio de Janeiro", name_en:"Rio de Janeiro", name_es:"Rio de Janeiro", name_fr:"Rio de Janeiro", lon:-43.17, lat:-22.91, cont:"SA"},
  {name_de:"Brasília", name_en:"Brasília", name_es:"Brasília", name_fr:"Brasília", lon:-47.93, lat:-15.78, cont:"SA"},
  {name_de:"Salvador", name_en:"Salvador", name_es:"Salvador", name_fr:"Salvador", lon:-38.48, lat:-12.97, cont:"SA"},
  {name_de:"Fortaleza", name_en:"Fortaleza", name_es:"Fortaleza", name_fr:"Fortaleza", lon:-38.54, lat:-3.73, cont:"SA"},
  {name_de:"Belo Horizonte", name_en:"Belo Horizonte", name_es:"Belo Horizonte", name_fr:"Belo Horizonte", lon:-43.94, lat:-19.92, cont:"SA"},
  {name_de:"Porto Alegre", name_en:"Porto Alegre", name_es:"Porto Alegre", name_fr:"Porto Alegre", lon:-51.23, lat:-30.03, cont:"SA"},
  {name_de:"Buenos Aires", name_en:"Buenos Aires", name_es:"Buenos Aires", name_fr:"Buenos Aires", lon:-58.38, lat:-34.6, cont:"SA"},
  {name_de:"Córdoba", name_en:"Córdoba", name_es:"Córdoba", name_fr:"Córdoba", lon:-64.18, lat:-31.42, cont:"SA"},
  {name_de:"Lima", name_en:"Lima", name_es:"Lima", name_fr:"Lima", lon:-77.03, lat:-12.05, cont:"SA"},
  {name_de:"Bogotá", name_en:"Bogotá", name_es:"Bogotá", name_fr:"Bogotá", lon:-74.07, lat:4.71, cont:"SA"},
  {name_de:"Medellín", name_en:"Medellín", name_es:"Medellín", name_fr:"Medellín", lon:-75.56, lat:6.25, cont:"SA"},
  {name_de:"Cali", name_en:"Cali", name_es:"Cali", name_fr:"Cali", lon:-76.53, lat:3.42, cont:"SA"},
  {name_de:"Santiago", name_en:"Santiago", name_es:"Santiago", name_fr:"Santiago", lon:-70.65, lat:-33.46, cont:"SA"},
  {name_de:"Caracas", name_en:"Caracas", name_es:"Caracas", name_fr:"Caracas", lon:-66.9, lat:10.49, cont:"SA"},
  {name_de:"Quito", name_en:"Quito", name_es:"Quito", name_fr:"Quito", lon:-78.47, lat:-0.18, cont:"SA"},
  {name_de:"Guayaquil", name_en:"Guayaquil", name_es:"Guayaquil", name_fr:"Guayaquil", lon:-79.89, lat:-2.19, cont:"SA"},
  {name_de:"La Paz", name_en:"La Paz", name_es:"La Paz", name_fr:"La Paz", lon:-68.15, lat:-16.5, cont:"SA"},
  {name_de:"Montevideo", name_en:"Montevideo", name_es:"Montevideo", name_fr:"Montevideo", lon:-56.19, lat:-34.9, cont:"SA"},
  {name_de:"Asunción", name_en:"Asunción", name_es:"Asunción", name_fr:"Asunción", lon:-57.58, lat:-25.28, cont:"SA"},
  {name_de:"Sydney", name_en:"Sydney", name_es:"Sydney", name_fr:"Sydney", lon:151.21, lat:-33.87, cont:"OC"},
  {name_de:"Melbourne", name_en:"Melbourne", name_es:"Melbourne", name_fr:"Melbourne", lon:144.96, lat:-37.81, cont:"OC"},
  {name_de:"Brisbane", name_en:"Brisbane", name_es:"Brisbane", name_fr:"Brisbane", lon:153.03, lat:-27.47, cont:"OC"},
  {name_de:"Perth", name_en:"Perth", name_es:"Perth", name_fr:"Perth", lon:115.86, lat:-31.95, cont:"OC"},
  {name_de:"Adelaide", name_en:"Adelaide", name_es:"Adelaide", name_fr:"Adelaide", lon:138.6, lat:-34.93, cont:"OC"},
  {name_de:"Canberra", name_en:"Canberra", name_es:"Canberra", name_fr:"Canberra", lon:149.13, lat:-35.28, cont:"OC"},
  {name_de:"Gold Coast", name_en:"Gold Coast", name_es:"Gold Coast", name_fr:"Gold Coast", lon:153.43, lat:-28, cont:"OC"},
  {name_de:"Hobart", name_en:"Hobart", name_es:"Hobart", name_fr:"Hobart", lon:147.33, lat:-42.88, cont:"OC"},
  {name_de:"Auckland", name_en:"Auckland", name_es:"Auckland", name_fr:"Auckland", lon:174.76, lat:-36.85, cont:"OC"},
  {name_de:"Wellington", name_en:"Wellington", name_es:"Wellington", name_fr:"Wellington", lon:174.78, lat:-41.29, cont:"OC"},
  {name_de:"Christchurch", name_en:"Christchurch", name_es:"Christchurch", name_fr:"Christchurch", lon:172.64, lat:-43.53, cont:"OC"},
  {name_de:"Suva", name_en:"Suva", name_es:"Suva", name_fr:"Suva", lon:178.44, lat:-18.14, cont:"OC"},
  {name_de:"Port Moresby", name_en:"Port Moresby", name_es:"Port Moresby", name_fr:"Port Moresby", lon:147.18, lat:-9.44, cont:"OC"},
  {name_de:"Nouméa", name_en:"Nouméa", name_es:"Nouméa", name_fr:"Nouméa", lon:166.46, lat:-22.28, cont:"OC"},
  {name_de:"Peking", name_en:"Beijing", name_es:"Pekín", name_fr:"Pékin", lon:116.41, lat:39.9, cont:"AS", country:"CN"},
  {name_de:"Shanghai", name_en:"Shanghai", name_es:"Shanghai", name_fr:"Shanghai", lon:121.47, lat:31.23, cont:"AS", country:"CN"},
  {name_de:"Guangzhou", name_en:"Guangzhou", name_es:"Guangzhou", name_fr:"Guangzhou", lon:113.26, lat:23.13, cont:"AS", country:"CN"},
  {name_de:"Shenzhen", name_en:"Shenzhen", name_es:"Shenzhen", name_fr:"Shenzhen", lon:114.07, lat:22.54, cont:"AS", country:"CN"},
  {name_de:"Chengdu", name_en:"Chengdu", name_es:"Chengdu", name_fr:"Chengdu", lon:104.07, lat:30.57, cont:"AS", country:"CN"},
  {name_de:"Chongqing", name_en:"Chongqing", name_es:"Chongqing", name_fr:"Chongqing", lon:106.55, lat:29.56, cont:"AS", country:"CN"},
  {name_de:"Tianjin", name_en:"Tianjin", name_es:"Tianjin", name_fr:"Tianjin", lon:117.2, lat:39.13, cont:"AS", country:"CN"},
  {name_de:"Wuhan", name_en:"Wuhan", name_es:"Wuhan", name_fr:"Wuhan", lon:114.31, lat:30.59, cont:"AS", country:"CN"},
  {name_de:"Hangzhou", name_en:"Hangzhou", name_es:"Hangzhou", name_fr:"Hangzhou", lon:120.15, lat:30.27, cont:"AS", country:"CN"},
  {name_de:"Nanjing", name_en:"Nanjing", name_es:"Nanjing", name_fr:"Nanjing", lon:118.8, lat:32.06, cont:"AS", country:"CN"},
  {name_de:"Xi'an", name_en:"Xi'an", name_es:"Xi'an", name_fr:"Xi'an", lon:108.94, lat:34.26, cont:"AS", country:"CN"},
  {name_de:"Shenyang", name_en:"Shenyang", name_es:"Shenyang", name_fr:"Shenyang", lon:123.43, lat:41.8, cont:"AS", country:"CN"},
  {name_de:"Harbin", name_en:"Harbin", name_es:"Harbin", name_fr:"Harbin", lon:126.65, lat:45.75, cont:"AS", country:"CN"},
  {name_de:"Kunming", name_en:"Kunming", name_es:"Kunming", name_fr:"Kunming", lon:102.83, lat:25.04, cont:"AS", country:"CN"},
  {name_de:"Ürümqi", name_en:"Ürümqi", name_es:"Ürümqi", name_fr:"Ürümqi", lon:87.62, lat:43.83, cont:"AS", country:"CN"},
  {name_de:"Lhasa", name_en:"Lhasa", name_es:"Lhasa", name_fr:"Lhasa", lon:91.13, lat:29.65, cont:"AS", country:"CN"},
  {name_de:"Dalian", name_en:"Dalian", name_es:"Dalian", name_fr:"Dalian", lon:121.61, lat:38.91, cont:"AS", country:"CN"},
  {name_de:"Qingdao", name_en:"Qingdao", name_es:"Qingdao", name_fr:"Qingdao", lon:120.38, lat:36.07, cont:"AS", country:"CN"},
  {name_de:"Xiamen", name_en:"Xiamen", name_es:"Xiamen", name_fr:"Xiamen", lon:118.09, lat:24.48, cont:"AS", country:"CN"},
  {name_de:"Hongkong", name_en:"Hong Kong", name_es:"Hong Kong", name_fr:"Hong Kong", lon:114.17, lat:22.32, cont:"AS", country:"CN"},
  {name_de:"Tokio", name_en:"Tokyo", name_es:"Tokio", name_fr:"Tokyo", lon:139.69, lat:35.69, cont:"AS", country:"JP"},
  {name_de:"Osaka", name_en:"Osaka", name_es:"Osaka", name_fr:"Osaka", lon:135.5, lat:34.69, cont:"AS", country:"JP"},
  {name_de:"Yokohama", name_en:"Yokohama", name_es:"Yokohama", name_fr:"Yokohama", lon:139.64, lat:35.44, cont:"AS", country:"JP"},
  {name_de:"Nagoya", name_en:"Nagoya", name_es:"Nagoya", name_fr:"Nagoya", lon:136.91, lat:35.18, cont:"AS", country:"JP"},
  {name_de:"Sapporo", name_en:"Sapporo", name_es:"Sapporo", name_fr:"Sapporo", lon:141.35, lat:43.06, cont:"AS", country:"JP"},
  {name_de:"Fukuoka", name_en:"Fukuoka", name_es:"Fukuoka", name_fr:"Fukuoka", lon:130.42, lat:33.59, cont:"AS", country:"JP"},
  {name_de:"Kobe", name_en:"Kobe", name_es:"Kobe", name_fr:"Kobe", lon:135.19, lat:34.69, cont:"AS", country:"JP"},
  {name_de:"Kyoto", name_en:"Kyoto", name_es:"Kyoto", name_fr:"Kyoto", lon:135.77, lat:35.01, cont:"AS", country:"JP"},
  {name_de:"Hiroshima", name_en:"Hiroshima", name_es:"Hiroshima", name_fr:"Hiroshima", lon:132.46, lat:34.4, cont:"AS", country:"JP"},
  {name_de:"Sendai", name_en:"Sendai", name_es:"Sendai", name_fr:"Sendai", lon:140.87, lat:38.27, cont:"AS", country:"JP"},
  {name_de:"Naha", name_en:"Naha", name_es:"Naha", name_fr:"Naha", lon:127.68, lat:26.34, cont:"AS", country:"JP"},
  {name_de:"Nagasaki", name_en:"Nagasaki", name_es:"Nagasaki", name_fr:"Nagasaki", lon:129.87, lat:32.75, cont:"AS", country:"JP"},
  {name_de:"Niigata", name_en:"Niigata", name_es:"Niigata", name_fr:"Niigata", lon:139.02, lat:37.92, cont:"AS", country:"JP"},
  {name_de:"Kanazawa", name_en:"Kanazawa", name_es:"Kanazawa", name_fr:"Kanazawa", lon:136.63, lat:36.56, cont:"AS", country:"JP"},
  {name_de:"Kagoshima", name_en:"Kagoshima", name_es:"Kagoshima", name_fr:"Kagoshima", lon:130.56, lat:31.6, cont:"AS", country:"JP"},
  {name_de:"Neu-Delhi", name_en:"New Delhi", name_es:"Nueva Delhi", name_fr:"New Delhi", lon:77.21, lat:28.61, cont:"AS", country:"IN"},
  {name_de:"Mumbai", name_en:"Mumbai", name_es:"Mumbai", name_fr:"Mumbai", lon:72.88, lat:19.08, cont:"AS", country:"IN"},
  {name_de:"Bangalore", name_en:"Bangalore", name_es:"Bangalore", name_fr:"Bangalore", lon:77.59, lat:12.97, cont:"AS", country:"IN"},
  {name_de:"Kolkata", name_en:"Kolkata", name_es:"Kolkata", name_fr:"Kolkata", lon:88.36, lat:22.57, cont:"AS", country:"IN"},
  {name_de:"Chennai", name_en:"Chennai", name_es:"Chennai", name_fr:"Chennai", lon:80.27, lat:13.08, cont:"AS", country:"IN"},
  {name_de:"Hyderabad", name_en:"Hyderabad", name_es:"Hyderabad", name_fr:"Hyderabad", lon:78.47, lat:17.39, cont:"AS", country:"IN"},
  {name_de:"Ahmedabad", name_en:"Ahmedabad", name_es:"Ahmedabad", name_fr:"Ahmedabad", lon:72.57, lat:23.02, cont:"AS", country:"IN"},
  {name_de:"Pune", name_en:"Pune", name_es:"Pune", name_fr:"Pune", lon:73.86, lat:18.52, cont:"AS", country:"IN"},
  {name_de:"Jaipur", name_en:"Jaipur", name_es:"Jaipur", name_fr:"Jaipur", lon:75.79, lat:26.92, cont:"AS", country:"IN"},
  {name_de:"Lucknow", name_en:"Lucknow", name_es:"Lucknow", name_fr:"Lucknow", lon:80.95, lat:26.85, cont:"AS", country:"IN"},
  {name_de:"Kochi", name_en:"Kochi", name_es:"Kochi", name_fr:"Kochi", lon:76.27, lat:9.93, cont:"AS", country:"IN"},
  {name_de:"Guwahati", name_en:"Guwahati", name_es:"Guwahati", name_fr:"Guwahati", lon:91.75, lat:26.14, cont:"AS", country:"IN"},
  {name_de:"Amritsar", name_en:"Amritsar", name_es:"Amritsar", name_fr:"Amritsar", lon:74.87, lat:31.63, cont:"AS", country:"IN"},
  {name_de:"Varanasi", name_en:"Varanasi", name_es:"Varanasi", name_fr:"Varanasi", lon:83, lat:25.32, cont:"AS", country:"IN"},
  {name_de:"Chandigarh", name_en:"Chandigarh", name_es:"Chandigarh", name_fr:"Chandigarh", lon:76.78, lat:30.73, cont:"AS", country:"IN"},
  {name_de:"São Paulo", name_en:"São Paulo", name_es:"São Paulo", name_fr:"São Paulo", lon:-46.63, lat:-23.55, cont:"SA", country:"BR"},
  {name_de:"Rio de Janeiro", name_en:"Rio de Janeiro", name_es:"Rio de Janeiro", name_fr:"Rio de Janeiro", lon:-43.17, lat:-22.91, cont:"SA", country:"BR"},
  {name_de:"Brasília", name_en:"Brasília", name_es:"Brasília", name_fr:"Brasília", lon:-47.93, lat:-15.78, cont:"SA", country:"BR"},
  {name_de:"Salvador", name_en:"Salvador", name_es:"Salvador", name_fr:"Salvador", lon:-38.48, lat:-12.97, cont:"SA", country:"BR"},
  {name_de:"Fortaleza", name_en:"Fortaleza", name_es:"Fortaleza", name_fr:"Fortaleza", lon:-38.54, lat:-3.73, cont:"SA", country:"BR"},
  {name_de:"Belo Horizonte", name_en:"Belo Horizonte", name_es:"Belo Horizonte", name_fr:"Belo Horizonte", lon:-43.94, lat:-19.92, cont:"SA", country:"BR"},
  {name_de:"Porto Alegre", name_en:"Porto Alegre", name_es:"Porto Alegre", name_fr:"Porto Alegre", lon:-51.23, lat:-30.03, cont:"SA", country:"BR"},
  {name_de:"Manaus", name_en:"Manaus", name_es:"Manaus", name_fr:"Manaus", lon:-60.03, lat:-3.12, cont:"SA", country:"BR"},
  {name_de:"Recife", name_en:"Recife", name_es:"Recife", name_fr:"Recife", lon:-34.87, lat:-8.05, cont:"SA", country:"BR"},
  {name_de:"Curitiba", name_en:"Curitiba", name_es:"Curitiba", name_fr:"Curitiba", lon:-49.27, lat:-25.43, cont:"SA", country:"BR"},
  {name_de:"Belém", name_en:"Belém", name_es:"Belém", name_fr:"Belém", lon:-48.5, lat:-1.46, cont:"SA", country:"BR"},
  {name_de:"Goiânia", name_en:"Goiânia", name_es:"Goiânia", name_fr:"Goiânia", lon:-49.25, lat:-16.69, cont:"SA", country:"BR"},
  {name_de:"Campo Grande", name_en:"Campo Grande", name_es:"Campo Grande", name_fr:"Campo Grande", lon:-54.62, lat:-20.44, cont:"SA", country:"BR"},
  {name_de:"Florianópolis", name_en:"Florianópolis", name_es:"Florianópolis", name_fr:"Florianópolis", lon:-48.55, lat:-27.6, cont:"SA", country:"BR"},
  {name_de:"Natal", name_en:"Natal", name_es:"Natal", name_fr:"Natal", lon:-35.21, lat:-5.79, cont:"SA", country:"BR"},
  {name_de:"Sydney", name_en:"Sydney", name_es:"Sydney", name_fr:"Sydney", lon:151.21, lat:-33.87, cont:"OC", country:"AU"},
  {name_de:"Melbourne", name_en:"Melbourne", name_es:"Melbourne", name_fr:"Melbourne", lon:144.96, lat:-37.81, cont:"OC", country:"AU"},
  {name_de:"Brisbane", name_en:"Brisbane", name_es:"Brisbane", name_fr:"Brisbane", lon:153.03, lat:-27.47, cont:"OC", country:"AU"},
  {name_de:"Perth", name_en:"Perth", name_es:"Perth", name_fr:"Perth", lon:115.86, lat:-31.95, cont:"OC", country:"AU"},
  {name_de:"Adelaide", name_en:"Adelaide", name_es:"Adelaide", name_fr:"Adelaide", lon:138.6, lat:-34.93, cont:"OC", country:"AU"},
  {name_de:"Canberra", name_en:"Canberra", name_es:"Canberra", name_fr:"Canberra", lon:149.13, lat:-35.28, cont:"OC", country:"AU"},
  {name_de:"Gold Coast", name_en:"Gold Coast", name_es:"Gold Coast", name_fr:"Gold Coast", lon:153.43, lat:-28, cont:"OC", country:"AU"},
  {name_de:"Hobart", name_en:"Hobart", name_es:"Hobart", name_fr:"Hobart", lon:147.33, lat:-42.88, cont:"OC", country:"AU"},
  {name_de:"Darwin", name_en:"Darwin", name_es:"Darwin", name_fr:"Darwin", lon:130.84, lat:-12.46, cont:"OC", country:"AU"},
  {name_de:"Cairns", name_en:"Cairns", name_es:"Cairns", name_fr:"Cairns", lon:145.77, lat:-16.92, cont:"OC", country:"AU"},
  {name_de:"Townsville", name_en:"Townsville", name_es:"Townsville", name_fr:"Townsville", lon:146.78, lat:-19.26, cont:"OC", country:"AU"},
  {name_de:"Alice Springs", name_en:"Alice Springs", name_es:"Alice Springs", name_fr:"Alice Springs", lon:133.88, lat:-23.7, cont:"OC", country:"AU"},
  {name_de:"Broome", name_en:"Broome", name_es:"Broome", name_fr:"Broome", lon:122.24, lat:-17.96, cont:"OC", country:"AU"},
  {name_de:"Geelong", name_en:"Geelong", name_es:"Geelong", name_fr:"Geelong", lon:144.35, lat:-38.15, cont:"OC", country:"AU"},
  {name_de:"Newcastle", name_en:"Newcastle", name_es:"Newcastle", name_fr:"Newcastle", lon:151.78, lat:-32.93, cont:"OC", country:"AU"},
  {name_de:"Mexiko-Stadt", name_en:"Mexico City", name_es:"Ciudad de México", name_fr:"Mexico", lon:-99.13, lat:19.43, cont:"NA", country:"MX"},
  {name_de:"Guadalajara", name_en:"Guadalajara", name_es:"Guadalajara", name_fr:"Guadalajara", lon:-103.35, lat:20.66, cont:"NA", country:"MX"},
  {name_de:"Monterrey", name_en:"Monterrey", name_es:"Monterrey", name_fr:"Monterrey", lon:-100.32, lat:25.69, cont:"NA", country:"MX"},
  {name_de:"Puebla", name_en:"Puebla", name_es:"Puebla", name_fr:"Puebla", lon:-98.21, lat:19.04, cont:"NA", country:"MX"},
  {name_de:"Tijuana", name_en:"Tijuana", name_es:"Tijuana", name_fr:"Tijuana", lon:-117.02, lat:32.53, cont:"NA", country:"MX"},
  {name_de:"León", name_en:"León", name_es:"León", name_fr:"León", lon:-101.68, lat:21.12, cont:"NA", country:"MX"},
  {name_de:"Ciudad Juárez", name_en:"Ciudad Juárez", name_es:"Ciudad Juárez", name_fr:"Ciudad Juárez", lon:-106.44, lat:31.69, cont:"NA", country:"MX"},
  {name_de:"Mérida", name_en:"Mérida", name_es:"Mérida", name_fr:"Mérida", lon:-89.62, lat:20.97, cont:"NA", country:"MX"},
  {name_de:"Cancún", name_en:"Cancún", name_es:"Cancún", name_fr:"Cancún", lon:-86.85, lat:21.16, cont:"NA", country:"MX"},
  {name_de:"Acapulco", name_en:"Acapulco", name_es:"Acapulco", name_fr:"Acapulco", lon:-99.88, lat:16.86, cont:"NA", country:"MX"},
  {name_de:"Oaxaca", name_en:"Oaxaca", name_es:"Oaxaca", name_fr:"Oaxaca", lon:-96.73, lat:17.06, cont:"NA", country:"MX"},
  {name_de:"Hermosillo", name_en:"Hermosillo", name_es:"Hermosillo", name_fr:"Hermosillo", lon:-110.97, lat:29.07, cont:"NA", country:"MX"},
  {name_de:"Veracruz", name_en:"Veracruz", name_es:"Veracruz", name_fr:"Veracruz", lon:-96.13, lat:19.18, cont:"NA", country:"MX"},
  {name_de:"Chihuahua", name_en:"Chihuahua", name_es:"Chihuahua", name_fr:"Chihuahua", lon:-106.09, lat:28.63, cont:"NA", country:"MX"},
  {name_de:"Querétaro", name_en:"Querétaro", name_es:"Querétaro", name_fr:"Querétaro", lon:-100.39, lat:20.59, cont:"NA", country:"MX"}
];

const PIN_COUNTRY_KEYS=['DE','FR','US','CN','JP','IN','BR','AU','MX'];

const PIN_DECAY={
  DE:120,FR:200,JP:200,
  IN:500,CN:600,BR:700,US:700,AU:700,MX:400,
  EU:500,AF:800,AS:1000,NA:800,SA:800,OC:800,world:1200,trivia:900
};

// Drop-A-Pin-Trivia: welt­weit verstreute geografische Wahrzeichen/Besonderheiten ohne
// festen Regionsbezug (keine Stadt-Population, sondern "wo liegt X?").
const PIN_TRIVIA = [
  {name_de:"Stonehenge", name_en:"Stonehenge", name_es:"Stonehenge", name_fr:"Stonehenge", lon:-1.8262, lat:51.1789},
  {name_de:"Beringstraße", name_en:"Bering Strait", name_es:"Estrecho de Bering", name_fr:"Détroit de Béring", lon:-169, lat:65.75},
  {name_de:"Machu Picchu", name_en:"Machu Picchu", name_es:"Machu Picchu", name_fr:"Machu Picchu", lon:-72.545, lat:-13.1631},
  {name_de:"Mount Everest", name_en:"Mount Everest", name_es:"Monte Everest", name_fr:"Mont Everest", lon:86.925, lat:27.9881},
  {name_de:"Grand Canyon", name_en:"Grand Canyon", name_es:"Gran Cañón", name_fr:"Grand Canyon", lon:-112.1129, lat:36.1069},
  {name_de:"Victoriafälle", name_en:"Victoria Falls", name_es:"Cataratas Victoria", name_fr:"Chutes Victoria", lon:25.8572, lat:-17.9243},
  {name_de:"Totes Meer", name_en:"Dead Sea", name_es:"Mar Muerto", name_fr:"Mer Morte", lon:35.47, lat:31.5},
  {name_de:"Angkor Wat", name_en:"Angkor Wat", name_es:"Angkor Wat", name_fr:"Angkor Vat", lon:103.867, lat:13.4125},
  {name_de:"Petra", name_en:"Petra", name_es:"Petra", name_fr:"Pétra", lon:35.4444, lat:30.3285},
  {name_de:"Kap der Guten Hoffnung", name_en:"Cape of Good Hope", name_es:"Cabo de Buena Esperanza", name_fr:"Cap de Bonne-Espérance", lon:18.474, lat:-34.3568},
  {name_de:"Straße von Gibraltar", name_en:"Strait of Gibraltar", name_es:"Estrecho de Gibraltar", name_fr:"Détroit de Gibraltar", lon:-5.6, lat:35.95},
  {name_de:"Panamakanal", name_en:"Panama Canal", name_es:"Canal de Panamá", name_fr:"Canal de Panama", lon:-79.68, lat:9.08},
  {name_de:"Sueskanal", name_en:"Suez Canal", name_es:"Canal de Suez", name_fr:"Canal de Suez", lon:32.35, lat:30.5},
  {name_de:"Mont Blanc", name_en:"Mont Blanc", name_es:"Mont Blanc", name_fr:"Mont Blanc", lon:6.8652, lat:45.8326},
  {name_de:"Timbuktu", name_en:"Timbuktu", name_es:"Tombuctú", name_fr:"Tombouctou", lon:-3.0026, lat:16.7666},
  {name_de:"Death Valley", name_en:"Death Valley", name_es:"Valle de la Muerte", name_fr:"Vallée de la Mort", lon:-117.0794, lat:36.5054},
  {name_de:"Nordkap", name_en:"North Cape", name_es:"Cabo Norte", name_fr:"Cap Nord", lon:25.7844, lat:71.1706},
  {name_de:"Osterinsel", name_en:"Easter Island", name_es:"Isla de Pascua", name_fr:"Île de Pâques", lon:-109.3497, lat:-27.1127},
  {name_de:"Galápagos-Inseln", name_en:"Galápagos Islands", name_es:"Islas Galápagos", name_fr:"Îles Galápagos", lon:-90.9656, lat:-0.9538},
  {name_de:"Great Barrier Reef", name_en:"Great Barrier Reef", name_es:"Gran Barrera de Coral", name_fr:"Grande Barrière de corail", lon:147.6992, lat:-18.2871},
  {name_de:"Tschernobyl", name_en:"Chernobyl", name_es:"Chernóbil", name_fr:"Tchernobyl", lon:30.0995, lat:51.389},
  {name_de:"Amazonas-Mündung", name_en:"Amazon River Mouth", name_es:"Desembocadura del Amazonas", name_fr:"Embouchure de l’Amazone", lon:-50.05, lat:-0.05}
];

function getPinCities(region){
  if(!region||region==='world')return PIN_CITIES;
  if(region==='trivia')return PIN_TRIVIA;
  if(PIN_COUNTRY_KEYS.includes(region))return PIN_CITIES.filter(c=>c.country===region);
  return PIN_CITIES.filter(c=>c.cont===region);
}
