// Städte-Daten: {name_de, name_en, lon, lat, country}
const CITIES = {
  // Deutschland
  DE_BERLIN: {name_de:'Berlin', name_en:'Berlin', lon:13.405, lat:52.52, country:'DE', difficulty:'easy'},
  DE_MUNICH: {name_de:'München', name_en:'Munich', lon:11.582, lat:48.137, country:'DE', difficulty:'easy'},
  DE_HAMBURG: {name_de:'Hamburg', name_en:'Hamburg', lon:10.0, lat:53.55, country:'DE', difficulty:'easy'},
  DE_COLOGNE: {name_de:'Köln', name_en:'Cologne', lon:6.961, lat:50.938, country:'DE', difficulty:'medium'},
  DE_FRANKFURT: {name_de:'Frankfurt', name_en:'Frankfurt', lon:8.68, lat:50.11, country:'DE', difficulty:'medium'},
  DE_STUTTGART: {name_de:'Stuttgart', name_en:'Stuttgart', lon:9.11, lat:48.77, country:'DE', difficulty:'medium'},
  DE_DUSSELDORF: {name_de:'Düsseldorf', name_en:'Düsseldorf', lon:6.778, lat:51.227, country:'DE', difficulty:'hard'},
  DE_DRESDEN: {name_de:'Dresden', name_en:'Dresden', lon:13.733, lat:51.05, country:'DE', difficulty:'hard'},

  // USA
  US_NYC: {name_de:'New York', name_en:'New York', lon:-74.006, lat:40.713, country:'US', difficulty:'easy'},
  US_LA: {name_de:'Los Angeles', name_en:'Los Angeles', lon:-118.243, lat:34.052, country:'US', difficulty:'easy'},
  US_CHICAGO: {name_de:'Chicago', name_en:'Chicago', lon:-87.629, lat:41.878, country:'US', difficulty:'easy'},
  US_HOUSTON: {name_de:'Houston', name_en:'Houston', lon:-95.369, lat:29.760, country:'US', difficulty:'medium'},
  US_PHOENIX: {name_de:'Phoenix', name_en:'Phoenix', lon:-112.074, lat:33.448, country:'US', difficulty:'medium'},
  US_MIAMI: {name_de:'Miami', name_en:'Miami', lon:-80.194, lat:25.761, country:'US', difficulty:'medium'},
  US_DENVER: {name_de:'Denver', name_en:'Denver', lon:-104.990, lat:39.739, country:'US', difficulty:'hard'},
  US_SEATTLE: {name_de:'Seattle', name_en:'Seattle', lon:-122.332, lat:47.606, country:'US', difficulty:'hard'},

  // Frankreich
  FR_PARIS: {name_de:'Paris', name_en:'Paris', lon:2.352, lat:48.856, country:'FR', difficulty:'easy'},
  FR_MARSEILLE: {name_de:'Marseille', name_en:'Marseille', lon:5.397, lat:43.296, country:'FR', difficulty:'easy'},
  FR_LYON: {name_de:'Lyon', name_en:'Lyon', lon:4.836, lat:45.764, country:'FR', difficulty:'easy'},
  FR_TOULOUSE: {name_de:'Toulouse', name_en:'Toulouse', lon:1.443, lat:43.604, country:'FR', difficulty:'medium'},
  FR_NICE: {name_de:'Nizza', name_en:'Nice', lon:7.262, lat:43.710, country:'FR', difficulty:'medium'},
  FR_NANTES: {name_de:'Nantes', name_en:'Nantes', lon:-1.552, lat:47.218, country:'FR', difficulty:'medium'},
  FR_STRASBOURG: {name_de:'Straßburg', name_en:'Strasbourg', lon:7.753, lat:48.573, country:'FR', difficulty:'hard'},
  FR_BORDEAUX: {name_de:'Bordeaux', name_en:'Bordeaux', lon:-0.576, lat:44.841, country:'FR', difficulty:'hard'}
};

// Länder-Gruppen für Quiz-Modi
const CITY_COUNTRIES = {
  DE: {label_de:'Deutschland', label_en:'Germany', cities:Object.entries(CITIES).filter(([k,v])=>v.country==='DE').map(([k,v])=>v)},
  US: {label_de:'USA', label_en:'USA', cities:Object.entries(CITIES).filter(([k,v])=>v.country==='US').map(([k,v])=>v)},
  FR: {label_de:'Frankreich', label_en:'France', cities:Object.entries(CITIES).filter(([k,v])=>v.country==='FR').map(([k,v])=>v)}
};

function getCitiesByDifficulty(country, difficulty) {
  if(!CITY_COUNTRIES[country]) return [];
  return CITY_COUNTRIES[country].cities.filter(c=>c.difficulty===difficulty);
}

function getAllCitiesByDifficulty(difficulty) {
  return Object.values(CITIES).filter(c=>c.difficulty===difficulty);
}

// Drop-A-Pin: große Städte-Datenbank. cont = Kontinent (EU/AF/AS/NA/SA/OC),
// country = DE/FR/US für die Länder-spezifischen Quizze (diese Städte sind zugleich Teil ihres Kontinents).
const PIN_CITIES = [
  // ── EUROPA (ohne DE/FR) ──
  {name_de:'London', name_en:'London', lon:-0.13, lat:51.51, cont:'EU'},
  {name_de:'Edinburgh', name_en:'Edinburgh', lon:-3.19, lat:55.95, cont:'EU'},
  {name_de:'Manchester', name_en:'Manchester', lon:-2.24, lat:53.48, cont:'EU'},
  {name_de:'Dublin', name_en:'Dublin', lon:-6.26, lat:53.35, cont:'EU'},
  {name_de:'Madrid', name_en:'Madrid', lon:-3.70, lat:40.42, cont:'EU'},
  {name_de:'Barcelona', name_en:'Barcelona', lon:2.17, lat:41.39, cont:'EU'},
  {name_de:'Sevilla', name_en:'Seville', lon:-5.98, lat:37.39, cont:'EU'},
  {name_de:'Lissabon', name_en:'Lisbon', lon:-9.14, lat:38.72, cont:'EU'},
  {name_de:'Porto', name_en:'Porto', lon:-8.61, lat:41.15, cont:'EU'},
  {name_de:'Rom', name_en:'Rome', lon:12.50, lat:41.90, cont:'EU'},
  {name_de:'Mailand', name_en:'Milan', lon:9.19, lat:45.46, cont:'EU'},
  {name_de:'Neapel', name_en:'Naples', lon:14.27, lat:40.85, cont:'EU'},
  {name_de:'Venedig', name_en:'Venice', lon:12.34, lat:45.44, cont:'EU'},
  {name_de:'Amsterdam', name_en:'Amsterdam', lon:4.90, lat:52.37, cont:'EU'},
  {name_de:'Rotterdam', name_en:'Rotterdam', lon:4.48, lat:51.92, cont:'EU'},
  {name_de:'Brüssel', name_en:'Brussels', lon:4.35, lat:50.85, cont:'EU'},
  {name_de:'Wien', name_en:'Vienna', lon:16.37, lat:48.21, cont:'EU'},
  {name_de:'Zürich', name_en:'Zurich', lon:8.54, lat:47.37, cont:'EU'},
  {name_de:'Genf', name_en:'Geneva', lon:6.14, lat:46.20, cont:'EU'},
  {name_de:'Bern', name_en:'Bern', lon:7.45, lat:46.95, cont:'EU'},
  {name_de:'Warschau', name_en:'Warsaw', lon:21.01, lat:52.23, cont:'EU'},
  {name_de:'Krakau', name_en:'Krakow', lon:19.94, lat:50.06, cont:'EU'},
  {name_de:'Prag', name_en:'Prague', lon:14.44, lat:50.08, cont:'EU'},
  {name_de:'Budapest', name_en:'Budapest', lon:19.04, lat:47.50, cont:'EU'},
  {name_de:'Bratislava', name_en:'Bratislava', lon:17.11, lat:48.15, cont:'EU'},
  {name_de:'Stockholm', name_en:'Stockholm', lon:18.07, lat:59.33, cont:'EU'},
  {name_de:'Göteborg', name_en:'Gothenburg', lon:11.97, lat:57.71, cont:'EU'},
  {name_de:'Oslo', name_en:'Oslo', lon:10.75, lat:59.91, cont:'EU'},
  {name_de:'Kopenhagen', name_en:'Copenhagen', lon:12.57, lat:55.68, cont:'EU'},
  {name_de:'Helsinki', name_en:'Helsinki', lon:24.94, lat:60.17, cont:'EU'},
  {name_de:'Reykjavík', name_en:'Reykjavik', lon:-21.83, lat:64.13, cont:'EU'},
  {name_de:'Athen', name_en:'Athens', lon:23.73, lat:37.98, cont:'EU'},
  {name_de:'Thessaloniki', name_en:'Thessaloniki', lon:22.94, lat:40.64, cont:'EU'},
  {name_de:'Bukarest', name_en:'Bucharest', lon:26.10, lat:44.43, cont:'EU'},
  {name_de:'Sofia', name_en:'Sofia', lon:23.32, lat:42.70, cont:'EU'},
  {name_de:'Belgrad', name_en:'Belgrade', lon:20.46, lat:44.79, cont:'EU'},
  {name_de:'Zagreb', name_en:'Zagreb', lon:15.98, lat:45.81, cont:'EU'},
  {name_de:'Ljubljana', name_en:'Ljubljana', lon:14.51, lat:46.06, cont:'EU'},
  {name_de:'Tallinn', name_en:'Tallinn', lon:24.75, lat:59.44, cont:'EU'},
  {name_de:'Riga', name_en:'Riga', lon:24.11, lat:56.95, cont:'EU'},
  {name_de:'Vilnius', name_en:'Vilnius', lon:25.28, lat:54.69, cont:'EU'},
  {name_de:'Kiew', name_en:'Kyiv', lon:30.52, lat:50.45, cont:'EU'},
  {name_de:'Moskau', name_en:'Moscow', lon:37.62, lat:55.76, cont:'EU'},
  {name_de:'Sankt Petersburg', name_en:'St. Petersburg', lon:30.34, lat:59.93, cont:'EU'},

  // ── DEUTSCHLAND (cont EU, country DE) ──
  {name_de:'Berlin', name_en:'Berlin', lon:13.40, lat:52.52, cont:'EU', country:'DE'},
  {name_de:'Hamburg', name_en:'Hamburg', lon:10.00, lat:53.55, cont:'EU', country:'DE'},
  {name_de:'München', name_en:'Munich', lon:11.58, lat:48.14, cont:'EU', country:'DE'},
  {name_de:'Köln', name_en:'Cologne', lon:6.96, lat:50.94, cont:'EU', country:'DE'},
  {name_de:'Frankfurt', name_en:'Frankfurt', lon:8.68, lat:50.11, cont:'EU', country:'DE'},
  {name_de:'Stuttgart', name_en:'Stuttgart', lon:9.18, lat:48.78, cont:'EU', country:'DE'},
  {name_de:'Düsseldorf', name_en:'Düsseldorf', lon:6.78, lat:51.23, cont:'EU', country:'DE'},
  {name_de:'Dortmund', name_en:'Dortmund', lon:7.47, lat:51.51, cont:'EU', country:'DE'},
  {name_de:'Essen', name_en:'Essen', lon:7.01, lat:51.46, cont:'EU', country:'DE'},
  {name_de:'Leipzig', name_en:'Leipzig', lon:12.37, lat:51.34, cont:'EU', country:'DE'},
  {name_de:'Dresden', name_en:'Dresden', lon:13.74, lat:51.05, cont:'EU', country:'DE'},
  {name_de:'Hannover', name_en:'Hanover', lon:9.73, lat:52.37, cont:'EU', country:'DE'},
  {name_de:'Nürnberg', name_en:'Nuremberg', lon:11.08, lat:49.45, cont:'EU', country:'DE'},
  {name_de:'Bremen', name_en:'Bremen', lon:8.80, lat:53.08, cont:'EU', country:'DE'},
  {name_de:'Duisburg', name_en:'Duisburg', lon:6.76, lat:51.43, cont:'EU', country:'DE'},
  {name_de:'Bonn', name_en:'Bonn', lon:7.10, lat:50.74, cont:'EU', country:'DE'},
  {name_de:'Münster', name_en:'Münster', lon:7.63, lat:51.96, cont:'EU', country:'DE'},
  {name_de:'Karlsruhe', name_en:'Karlsruhe', lon:8.40, lat:49.01, cont:'EU', country:'DE'},
  {name_de:'Mannheim', name_en:'Mannheim', lon:8.47, lat:49.49, cont:'EU', country:'DE'},
  {name_de:'Augsburg', name_en:'Augsburg', lon:10.90, lat:48.37, cont:'EU', country:'DE'},
  {name_de:'Wiesbaden', name_en:'Wiesbaden', lon:8.24, lat:50.08, cont:'EU', country:'DE'},
  {name_de:'Kiel', name_en:'Kiel', lon:10.14, lat:54.32, cont:'EU', country:'DE'},
  {name_de:'Freiburg', name_en:'Freiburg', lon:7.85, lat:47.99, cont:'EU', country:'DE'},
  {name_de:'Rostock', name_en:'Rostock', lon:12.14, lat:54.09, cont:'EU', country:'DE'},
  {name_de:'Saarbrücken', name_en:'Saarbrücken', lon:6.99, lat:49.23, cont:'EU', country:'DE'},

  // ── FRANKREICH (cont EU, country FR) ──
  {name_de:'Paris', name_en:'Paris', lon:2.35, lat:48.86, cont:'EU', country:'FR'},
  {name_de:'Marseille', name_en:'Marseille', lon:5.37, lat:43.30, cont:'EU', country:'FR'},
  {name_de:'Lyon', name_en:'Lyon', lon:4.84, lat:45.76, cont:'EU', country:'FR'},
  {name_de:'Toulouse', name_en:'Toulouse', lon:1.44, lat:43.60, cont:'EU', country:'FR'},
  {name_de:'Nizza', name_en:'Nice', lon:7.27, lat:43.70, cont:'EU', country:'FR'},
  {name_de:'Nantes', name_en:'Nantes', lon:-1.55, lat:47.22, cont:'EU', country:'FR'},
  {name_de:'Straßburg', name_en:'Strasbourg', lon:7.75, lat:48.57, cont:'EU', country:'FR'},
  {name_de:'Bordeaux', name_en:'Bordeaux', lon:-0.58, lat:44.84, cont:'EU', country:'FR'},
  {name_de:'Lille', name_en:'Lille', lon:3.06, lat:50.63, cont:'EU', country:'FR'},
  {name_de:'Montpellier', name_en:'Montpellier', lon:3.88, lat:43.61, cont:'EU', country:'FR'},
  {name_de:'Rennes', name_en:'Rennes', lon:-1.68, lat:48.11, cont:'EU', country:'FR'},
  {name_de:'Reims', name_en:'Reims', lon:4.03, lat:49.26, cont:'EU', country:'FR'},
  {name_de:'Le Havre', name_en:'Le Havre', lon:0.11, lat:49.49, cont:'EU', country:'FR'},
  {name_de:'Toulon', name_en:'Toulon', lon:5.93, lat:43.12, cont:'EU', country:'FR'},
  {name_de:'Grenoble', name_en:'Grenoble', lon:5.72, lat:45.19, cont:'EU', country:'FR'},
  {name_de:'Dijon', name_en:'Dijon', lon:5.04, lat:47.32, cont:'EU', country:'FR'},
  {name_de:'Brest', name_en:'Brest', lon:-4.49, lat:48.39, cont:'EU', country:'FR'},
  {name_de:'Nancy', name_en:'Nancy', lon:6.18, lat:48.69, cont:'EU', country:'FR'},

  // ── ASIEN ──
  {name_de:'Tokio', name_en:'Tokyo', lon:139.69, lat:35.69, cont:'AS'},
  {name_de:'Osaka', name_en:'Osaka', lon:135.50, lat:34.69, cont:'AS'},
  {name_de:'Peking', name_en:'Beijing', lon:116.41, lat:39.90, cont:'AS'},
  {name_de:'Shanghai', name_en:'Shanghai', lon:121.47, lat:31.23, cont:'AS'},
  {name_de:'Hongkong', name_en:'Hong Kong', lon:114.17, lat:22.32, cont:'AS'},
  {name_de:'Guangzhou', name_en:'Guangzhou', lon:113.26, lat:23.13, cont:'AS'},
  {name_de:'Seoul', name_en:'Seoul', lon:126.98, lat:37.57, cont:'AS'},
  {name_de:'Busan', name_en:'Busan', lon:129.08, lat:35.18, cont:'AS'},
  {name_de:'Neu-Delhi', name_en:'New Delhi', lon:77.21, lat:28.61, cont:'AS'},
  {name_de:'Mumbai', name_en:'Mumbai', lon:72.88, lat:19.08, cont:'AS'},
  {name_de:'Bangalore', name_en:'Bangalore', lon:77.59, lat:12.97, cont:'AS'},
  {name_de:'Kolkata', name_en:'Kolkata', lon:88.36, lat:22.57, cont:'AS'},
  {name_de:'Chennai', name_en:'Chennai', lon:80.27, lat:13.08, cont:'AS'},
  {name_de:'Bangkok', name_en:'Bangkok', lon:100.50, lat:13.76, cont:'AS'},
  {name_de:'Jakarta', name_en:'Jakarta', lon:106.85, lat:-6.21, cont:'AS'},
  {name_de:'Singapur', name_en:'Singapore', lon:103.82, lat:1.35, cont:'AS'},
  {name_de:'Kuala Lumpur', name_en:'Kuala Lumpur', lon:101.69, lat:3.14, cont:'AS'},
  {name_de:'Manila', name_en:'Manila', lon:120.98, lat:14.60, cont:'AS'},
  {name_de:'Hanoi', name_en:'Hanoi', lon:105.83, lat:21.03, cont:'AS'},
  {name_de:'Ho-Chi-Minh-Stadt', name_en:'Ho Chi Minh City', lon:106.66, lat:10.82, cont:'AS'},
  {name_de:'Taipeh', name_en:'Taipei', lon:121.56, lat:25.03, cont:'AS'},
  {name_de:'Dubai', name_en:'Dubai', lon:55.27, lat:25.20, cont:'AS'},
  {name_de:'Riad', name_en:'Riyadh', lon:46.72, lat:24.71, cont:'AS'},
  {name_de:'Teheran', name_en:'Tehran', lon:51.39, lat:35.69, cont:'AS'},
  {name_de:'Bagdad', name_en:'Baghdad', lon:44.36, lat:33.31, cont:'AS'},
  {name_de:'Jerusalem', name_en:'Jerusalem', lon:35.21, lat:31.77, cont:'AS'},
  {name_de:'Istanbul', name_en:'Istanbul', lon:28.98, lat:41.01, cont:'AS'},
  {name_de:'Ankara', name_en:'Ankara', lon:32.85, lat:39.93, cont:'AS'},
  {name_de:'Karachi', name_en:'Karachi', lon:67.01, lat:24.86, cont:'AS'},
  {name_de:'Lahore', name_en:'Lahore', lon:74.34, lat:31.55, cont:'AS'},
  {name_de:'Dhaka', name_en:'Dhaka', lon:90.41, lat:23.81, cont:'AS'},
  {name_de:'Almaty', name_en:'Almaty', lon:76.95, lat:43.24, cont:'AS'},
  {name_de:'Taschkent', name_en:'Tashkent', lon:69.24, lat:41.30, cont:'AS'},
  {name_de:'Colombo', name_en:'Colombo', lon:79.86, lat:6.93, cont:'AS'},
  {name_de:'Kathmandu', name_en:'Kathmandu', lon:85.32, lat:27.70, cont:'AS'},

  // ── AFRIKA ──
  {name_de:'Kairo', name_en:'Cairo', lon:31.24, lat:30.04, cont:'AF'},
  {name_de:'Alexandria', name_en:'Alexandria', lon:29.92, lat:31.20, cont:'AF'},
  {name_de:'Lagos', name_en:'Lagos', lon:3.38, lat:6.52, cont:'AF'},
  {name_de:'Abuja', name_en:'Abuja', lon:7.49, lat:9.06, cont:'AF'},
  {name_de:'Nairobi', name_en:'Nairobi', lon:36.82, lat:-1.29, cont:'AF'},
  {name_de:'Kapstadt', name_en:'Cape Town', lon:18.42, lat:-33.92, cont:'AF'},
  {name_de:'Johannesburg', name_en:'Johannesburg', lon:28.05, lat:-26.20, cont:'AF'},
  {name_de:'Durban', name_en:'Durban', lon:31.02, lat:-29.86, cont:'AF'},
  {name_de:'Casablanca', name_en:'Casablanca', lon:-7.59, lat:33.57, cont:'AF'},
  {name_de:'Marrakesch', name_en:'Marrakesh', lon:-7.98, lat:31.63, cont:'AF'},
  {name_de:'Tunis', name_en:'Tunis', lon:10.18, lat:36.81, cont:'AF'},
  {name_de:'Algier', name_en:'Algiers', lon:3.06, lat:36.75, cont:'AF'},
  {name_de:'Accra', name_en:'Accra', lon:-0.19, lat:5.60, cont:'AF'},
  {name_de:'Abidjan', name_en:'Abidjan', lon:-4.02, lat:5.36, cont:'AF'},
  {name_de:'Dakar', name_en:'Dakar', lon:-17.45, lat:14.69, cont:'AF'},
  {name_de:'Addis Abeba', name_en:'Addis Ababa', lon:38.76, lat:9.03, cont:'AF'},
  {name_de:'Daressalam', name_en:'Dar es Salaam', lon:39.28, lat:-6.79, cont:'AF'},
  {name_de:'Khartum', name_en:'Khartoum', lon:32.53, lat:15.50, cont:'AF'},
  {name_de:'Kinshasa', name_en:'Kinshasa', lon:15.31, lat:-4.32, cont:'AF'},
  {name_de:'Luanda', name_en:'Luanda', lon:13.23, lat:-8.84, cont:'AF'},
  {name_de:'Harare', name_en:'Harare', lon:31.05, lat:-17.83, cont:'AF'},
  {name_de:'Kampala', name_en:'Kampala', lon:32.58, lat:0.35, cont:'AF'},
  {name_de:'Tripolis', name_en:'Tripoli', lon:13.19, lat:32.89, cont:'AF'},
  {name_de:'Windhoek', name_en:'Windhoek', lon:17.08, lat:-22.56, cont:'AF'},
  {name_de:'Maputo', name_en:'Maputo', lon:32.57, lat:-25.97, cont:'AF'},

  // ── NORDAMERIKA (ohne US) ──
  {name_de:'Mexiko-Stadt', name_en:'Mexico City', lon:-99.13, lat:19.43, cont:'NA'},
  {name_de:'Guadalajara', name_en:'Guadalajara', lon:-103.35, lat:20.66, cont:'NA'},
  {name_de:'Monterrey', name_en:'Monterrey', lon:-100.32, lat:25.69, cont:'NA'},
  {name_de:'Toronto', name_en:'Toronto', lon:-79.38, lat:43.65, cont:'NA'},
  {name_de:'Montreal', name_en:'Montreal', lon:-73.57, lat:45.50, cont:'NA'},
  {name_de:'Vancouver', name_en:'Vancouver', lon:-123.12, lat:49.28, cont:'NA'},
  {name_de:'Ottawa', name_en:'Ottawa', lon:-75.70, lat:45.42, cont:'NA'},
  {name_de:'Calgary', name_en:'Calgary', lon:-114.07, lat:51.05, cont:'NA'},
  {name_de:'Havanna', name_en:'Havana', lon:-82.38, lat:23.11, cont:'NA'},
  {name_de:'Guatemala-Stadt', name_en:'Guatemala City', lon:-90.51, lat:14.63, cont:'NA'},
  {name_de:'Panama-Stadt', name_en:'Panama City', lon:-79.52, lat:8.98, cont:'NA'},
  {name_de:'San José', name_en:'San José', lon:-84.09, lat:9.93, cont:'NA'},
  {name_de:'Kingston', name_en:'Kingston', lon:-76.79, lat:17.97, cont:'NA'},
  {name_de:'Santo Domingo', name_en:'Santo Domingo', lon:-69.93, lat:18.49, cont:'NA'},

  // ── USA (cont NA, country US) ──
  {name_de:'New York', name_en:'New York', lon:-74.01, lat:40.71, cont:'NA', country:'US'},
  {name_de:'Los Angeles', name_en:'Los Angeles', lon:-118.24, lat:34.05, cont:'NA', country:'US'},
  {name_de:'Chicago', name_en:'Chicago', lon:-87.63, lat:41.88, cont:'NA', country:'US'},
  {name_de:'Houston', name_en:'Houston', lon:-95.37, lat:29.76, cont:'NA', country:'US'},
  {name_de:'Phoenix', name_en:'Phoenix', lon:-112.07, lat:33.45, cont:'NA', country:'US'},
  {name_de:'Philadelphia', name_en:'Philadelphia', lon:-75.17, lat:39.95, cont:'NA', country:'US'},
  {name_de:'San Antonio', name_en:'San Antonio', lon:-98.49, lat:29.42, cont:'NA', country:'US'},
  {name_de:'San Diego', name_en:'San Diego', lon:-117.16, lat:32.72, cont:'NA', country:'US'},
  {name_de:'Dallas', name_en:'Dallas', lon:-96.80, lat:32.78, cont:'NA', country:'US'},
  {name_de:'Austin', name_en:'Austin', lon:-97.74, lat:30.27, cont:'NA', country:'US'},
  {name_de:'San Francisco', name_en:'San Francisco', lon:-122.42, lat:37.77, cont:'NA', country:'US'},
  {name_de:'Seattle', name_en:'Seattle', lon:-122.33, lat:47.61, cont:'NA', country:'US'},
  {name_de:'Denver', name_en:'Denver', lon:-104.99, lat:39.74, cont:'NA', country:'US'},
  {name_de:'Washington', name_en:'Washington D.C.', lon:-77.04, lat:38.91, cont:'NA', country:'US'},
  {name_de:'Boston', name_en:'Boston', lon:-71.06, lat:42.36, cont:'NA', country:'US'},
  {name_de:'Miami', name_en:'Miami', lon:-80.19, lat:25.76, cont:'NA', country:'US'},
  {name_de:'Atlanta', name_en:'Atlanta', lon:-84.39, lat:33.75, cont:'NA', country:'US'},
  {name_de:'Las Vegas', name_en:'Las Vegas', lon:-115.14, lat:36.17, cont:'NA', country:'US'},
  {name_de:'Detroit', name_en:'Detroit', lon:-83.05, lat:42.33, cont:'NA', country:'US'},
  {name_de:'Minneapolis', name_en:'Minneapolis', lon:-93.27, lat:44.98, cont:'NA', country:'US'},
  {name_de:'New Orleans', name_en:'New Orleans', lon:-90.07, lat:29.95, cont:'NA', country:'US'},
  {name_de:'Portland', name_en:'Portland', lon:-122.68, lat:45.52, cont:'NA', country:'US'},
  {name_de:'Salt Lake City', name_en:'Salt Lake City', lon:-111.89, lat:40.76, cont:'NA', country:'US'},
  {name_de:'Kansas City', name_en:'Kansas City', lon:-94.58, lat:39.10, cont:'NA', country:'US'},
  {name_de:'St. Louis', name_en:'St. Louis', lon:-90.20, lat:38.63, cont:'NA', country:'US'},
  {name_de:'Honolulu', name_en:'Honolulu', lon:-157.86, lat:21.31, cont:'NA', country:'US'},

  // ── SÜDAMERIKA ──
  {name_de:'São Paulo', name_en:'São Paulo', lon:-46.63, lat:-23.55, cont:'SA'},
  {name_de:'Rio de Janeiro', name_en:'Rio de Janeiro', lon:-43.17, lat:-22.91, cont:'SA'},
  {name_de:'Brasília', name_en:'Brasília', lon:-47.93, lat:-15.78, cont:'SA'},
  {name_de:'Salvador', name_en:'Salvador', lon:-38.48, lat:-12.97, cont:'SA'},
  {name_de:'Fortaleza', name_en:'Fortaleza', lon:-38.54, lat:-3.73, cont:'SA'},
  {name_de:'Belo Horizonte', name_en:'Belo Horizonte', lon:-43.94, lat:-19.92, cont:'SA'},
  {name_de:'Porto Alegre', name_en:'Porto Alegre', lon:-51.23, lat:-30.03, cont:'SA'},
  {name_de:'Buenos Aires', name_en:'Buenos Aires', lon:-58.38, lat:-34.60, cont:'SA'},
  {name_de:'Córdoba', name_en:'Córdoba', lon:-64.18, lat:-31.42, cont:'SA'},
  {name_de:'Lima', name_en:'Lima', lon:-77.03, lat:-12.05, cont:'SA'},
  {name_de:'Bogotá', name_en:'Bogotá', lon:-74.07, lat:4.71, cont:'SA'},
  {name_de:'Medellín', name_en:'Medellín', lon:-75.56, lat:6.25, cont:'SA'},
  {name_de:'Cali', name_en:'Cali', lon:-76.53, lat:3.42, cont:'SA'},
  {name_de:'Santiago', name_en:'Santiago', lon:-70.65, lat:-33.46, cont:'SA'},
  {name_de:'Caracas', name_en:'Caracas', lon:-66.90, lat:10.49, cont:'SA'},
  {name_de:'Quito', name_en:'Quito', lon:-78.47, lat:-0.18, cont:'SA'},
  {name_de:'Guayaquil', name_en:'Guayaquil', lon:-79.89, lat:-2.19, cont:'SA'},
  {name_de:'La Paz', name_en:'La Paz', lon:-68.15, lat:-16.50, cont:'SA'},
  {name_de:'Montevideo', name_en:'Montevideo', lon:-56.19, lat:-34.90, cont:'SA'},
  {name_de:'Asunción', name_en:'Asunción', lon:-57.58, lat:-25.28, cont:'SA'},

  // ── OZEANIEN ──
  {name_de:'Sydney', name_en:'Sydney', lon:151.21, lat:-33.87, cont:'OC'},
  {name_de:'Melbourne', name_en:'Melbourne', lon:144.96, lat:-37.81, cont:'OC'},
  {name_de:'Brisbane', name_en:'Brisbane', lon:153.03, lat:-27.47, cont:'OC'},
  {name_de:'Perth', name_en:'Perth', lon:115.86, lat:-31.95, cont:'OC'},
  {name_de:'Adelaide', name_en:'Adelaide', lon:138.60, lat:-34.93, cont:'OC'},
  {name_de:'Canberra', name_en:'Canberra', lon:149.13, lat:-35.28, cont:'OC'},
  {name_de:'Gold Coast', name_en:'Gold Coast', lon:153.43, lat:-28.00, cont:'OC'},
  {name_de:'Hobart', name_en:'Hobart', lon:147.33, lat:-42.88, cont:'OC'},
  {name_de:'Auckland', name_en:'Auckland', lon:174.76, lat:-36.85, cont:'OC'},
  {name_de:'Wellington', name_en:'Wellington', lon:174.78, lat:-41.29, cont:'OC'},
  {name_de:'Christchurch', name_en:'Christchurch', lon:172.64, lat:-43.53, cont:'OC'},
  {name_de:'Suva', name_en:'Suva', lon:178.44, lat:-18.14, cont:'OC'},
  {name_de:'Port Moresby', name_en:'Port Moresby', lon:147.18, lat:-9.44, cont:'OC'},
  {name_de:'Nouméa', name_en:'Nouméa', lon:166.46, lat:-22.28, cont:'OC'},

  // ── CHINA (cont AS, country CN) ──
  {name_de:'Peking', name_en:'Beijing', lon:116.41, lat:39.90, cont:'AS', country:'CN'},
  {name_de:'Shanghai', name_en:'Shanghai', lon:121.47, lat:31.23, cont:'AS', country:'CN'},
  {name_de:'Guangzhou', name_en:'Guangzhou', lon:113.26, lat:23.13, cont:'AS', country:'CN'},
  {name_de:'Shenzhen', name_en:'Shenzhen', lon:114.07, lat:22.54, cont:'AS', country:'CN'},
  {name_de:'Chengdu', name_en:'Chengdu', lon:104.07, lat:30.57, cont:'AS', country:'CN'},
  {name_de:'Chongqing', name_en:'Chongqing', lon:106.55, lat:29.56, cont:'AS', country:'CN'},
  {name_de:'Tianjin', name_en:'Tianjin', lon:117.20, lat:39.13, cont:'AS', country:'CN'},
  {name_de:'Wuhan', name_en:'Wuhan', lon:114.31, lat:30.59, cont:'AS', country:'CN'},
  {name_de:'Hangzhou', name_en:'Hangzhou', lon:120.15, lat:30.27, cont:'AS', country:'CN'},
  {name_de:'Nanjing', name_en:'Nanjing', lon:118.80, lat:32.06, cont:'AS', country:'CN'},
  {name_de:'Xi\'an', name_en:'Xi\'an', lon:108.94, lat:34.26, cont:'AS', country:'CN'},
  {name_de:'Shenyang', name_en:'Shenyang', lon:123.43, lat:41.80, cont:'AS', country:'CN'},
  {name_de:'Harbin', name_en:'Harbin', lon:126.65, lat:45.75, cont:'AS', country:'CN'},
  {name_de:'Kunming', name_en:'Kunming', lon:102.83, lat:25.04, cont:'AS', country:'CN'},
  {name_de:'Ürümqi', name_en:'Ürümqi', lon:87.62, lat:43.83, cont:'AS', country:'CN'},
  {name_de:'Lhasa', name_en:'Lhasa', lon:91.13, lat:29.65, cont:'AS', country:'CN'},
  {name_de:'Dalian', name_en:'Dalian', lon:121.61, lat:38.91, cont:'AS', country:'CN'},
  {name_de:'Qingdao', name_en:'Qingdao', lon:120.38, lat:36.07, cont:'AS', country:'CN'},
  {name_de:'Xiamen', name_en:'Xiamen', lon:118.09, lat:24.48, cont:'AS', country:'CN'},
  {name_de:'Hongkong', name_en:'Hong Kong', lon:114.17, lat:22.32, cont:'AS', country:'CN'},

  // ── JAPAN (cont AS, country JP) ──
  {name_de:'Tokio', name_en:'Tokyo', lon:139.69, lat:35.69, cont:'AS', country:'JP'},
  {name_de:'Osaka', name_en:'Osaka', lon:135.50, lat:34.69, cont:'AS', country:'JP'},
  {name_de:'Yokohama', name_en:'Yokohama', lon:139.64, lat:35.44, cont:'AS', country:'JP'},
  {name_de:'Nagoya', name_en:'Nagoya', lon:136.91, lat:35.18, cont:'AS', country:'JP'},
  {name_de:'Sapporo', name_en:'Sapporo', lon:141.35, lat:43.06, cont:'AS', country:'JP'},
  {name_de:'Fukuoka', name_en:'Fukuoka', lon:130.42, lat:33.59, cont:'AS', country:'JP'},
  {name_de:'Kobe', name_en:'Kobe', lon:135.19, lat:34.69, cont:'AS', country:'JP'},
  {name_de:'Kyoto', name_en:'Kyoto', lon:135.77, lat:35.01, cont:'AS', country:'JP'},
  {name_de:'Hiroshima', name_en:'Hiroshima', lon:132.46, lat:34.40, cont:'AS', country:'JP'},
  {name_de:'Sendai', name_en:'Sendai', lon:140.87, lat:38.27, cont:'AS', country:'JP'},
  {name_de:'Naha', name_en:'Naha', lon:127.68, lat:26.34, cont:'AS', country:'JP'},
  {name_de:'Nagasaki', name_en:'Nagasaki', lon:129.87, lat:32.75, cont:'AS', country:'JP'},
  {name_de:'Niigata', name_en:'Niigata', lon:139.02, lat:37.92, cont:'AS', country:'JP'},
  {name_de:'Kanazawa', name_en:'Kanazawa', lon:136.63, lat:36.56, cont:'AS', country:'JP'},
  {name_de:'Kagoshima', name_en:'Kagoshima', lon:130.56, lat:31.60, cont:'AS', country:'JP'},

  // ── INDIEN (cont AS, country IN) ──
  {name_de:'Neu-Delhi', name_en:'New Delhi', lon:77.21, lat:28.61, cont:'AS', country:'IN'},
  {name_de:'Mumbai', name_en:'Mumbai', lon:72.88, lat:19.08, cont:'AS', country:'IN'},
  {name_de:'Bangalore', name_en:'Bangalore', lon:77.59, lat:12.97, cont:'AS', country:'IN'},
  {name_de:'Kolkata', name_en:'Kolkata', lon:88.36, lat:22.57, cont:'AS', country:'IN'},
  {name_de:'Chennai', name_en:'Chennai', lon:80.27, lat:13.08, cont:'AS', country:'IN'},
  {name_de:'Hyderabad', name_en:'Hyderabad', lon:78.47, lat:17.39, cont:'AS', country:'IN'},
  {name_de:'Ahmedabad', name_en:'Ahmedabad', lon:72.57, lat:23.02, cont:'AS', country:'IN'},
  {name_de:'Pune', name_en:'Pune', lon:73.86, lat:18.52, cont:'AS', country:'IN'},
  {name_de:'Jaipur', name_en:'Jaipur', lon:75.79, lat:26.92, cont:'AS', country:'IN'},
  {name_de:'Lucknow', name_en:'Lucknow', lon:80.95, lat:26.85, cont:'AS', country:'IN'},
  {name_de:'Kochi', name_en:'Kochi', lon:76.27, lat:9.93, cont:'AS', country:'IN'},
  {name_de:'Guwahati', name_en:'Guwahati', lon:91.75, lat:26.14, cont:'AS', country:'IN'},
  {name_de:'Amritsar', name_en:'Amritsar', lon:74.87, lat:31.63, cont:'AS', country:'IN'},
  {name_de:'Varanasi', name_en:'Varanasi', lon:83.00, lat:25.32, cont:'AS', country:'IN'},
  {name_de:'Chandigarh', name_en:'Chandigarh', lon:76.78, lat:30.73, cont:'AS', country:'IN'},

  // ── BRASILIEN (cont SA, country BR) ──
  {name_de:'São Paulo', name_en:'São Paulo', lon:-46.63, lat:-23.55, cont:'SA', country:'BR'},
  {name_de:'Rio de Janeiro', name_en:'Rio de Janeiro', lon:-43.17, lat:-22.91, cont:'SA', country:'BR'},
  {name_de:'Brasília', name_en:'Brasília', lon:-47.93, lat:-15.78, cont:'SA', country:'BR'},
  {name_de:'Salvador', name_en:'Salvador', lon:-38.48, lat:-12.97, cont:'SA', country:'BR'},
  {name_de:'Fortaleza', name_en:'Fortaleza', lon:-38.54, lat:-3.73, cont:'SA', country:'BR'},
  {name_de:'Belo Horizonte', name_en:'Belo Horizonte', lon:-43.94, lat:-19.92, cont:'SA', country:'BR'},
  {name_de:'Porto Alegre', name_en:'Porto Alegre', lon:-51.23, lat:-30.03, cont:'SA', country:'BR'},
  {name_de:'Manaus', name_en:'Manaus', lon:-60.03, lat:-3.12, cont:'SA', country:'BR'},
  {name_de:'Recife', name_en:'Recife', lon:-34.87, lat:-8.05, cont:'SA', country:'BR'},
  {name_de:'Curitiba', name_en:'Curitiba', lon:-49.27, lat:-25.43, cont:'SA', country:'BR'},
  {name_de:'Belém', name_en:'Belém', lon:-48.50, lat:-1.46, cont:'SA', country:'BR'},
  {name_de:'Goiânia', name_en:'Goiânia', lon:-49.25, lat:-16.69, cont:'SA', country:'BR'},
  {name_de:'Campo Grande', name_en:'Campo Grande', lon:-54.62, lat:-20.44, cont:'SA', country:'BR'},
  {name_de:'Florianópolis', name_en:'Florianópolis', lon:-48.55, lat:-27.60, cont:'SA', country:'BR'},
  {name_de:'Natal', name_en:'Natal', lon:-35.21, lat:-5.79, cont:'SA', country:'BR'},

  // ── AUSTRALIEN (cont OC, country AU) ──
  {name_de:'Sydney', name_en:'Sydney', lon:151.21, lat:-33.87, cont:'OC', country:'AU'},
  {name_de:'Melbourne', name_en:'Melbourne', lon:144.96, lat:-37.81, cont:'OC', country:'AU'},
  {name_de:'Brisbane', name_en:'Brisbane', lon:153.03, lat:-27.47, cont:'OC', country:'AU'},
  {name_de:'Perth', name_en:'Perth', lon:115.86, lat:-31.95, cont:'OC', country:'AU'},
  {name_de:'Adelaide', name_en:'Adelaide', lon:138.60, lat:-34.93, cont:'OC', country:'AU'},
  {name_de:'Canberra', name_en:'Canberra', lon:149.13, lat:-35.28, cont:'OC', country:'AU'},
  {name_de:'Gold Coast', name_en:'Gold Coast', lon:153.43, lat:-28.00, cont:'OC', country:'AU'},
  {name_de:'Hobart', name_en:'Hobart', lon:147.33, lat:-42.88, cont:'OC', country:'AU'},
  {name_de:'Darwin', name_en:'Darwin', lon:130.84, lat:-12.46, cont:'OC', country:'AU'},
  {name_de:'Cairns', name_en:'Cairns', lon:145.77, lat:-16.92, cont:'OC', country:'AU'},
  {name_de:'Townsville', name_en:'Townsville', lon:146.78, lat:-19.26, cont:'OC', country:'AU'},
  {name_de:'Alice Springs', name_en:'Alice Springs', lon:133.88, lat:-23.70, cont:'OC', country:'AU'},
  {name_de:'Broome', name_en:'Broome', lon:122.24, lat:-17.96, cont:'OC', country:'AU'},
  {name_de:'Geelong', name_en:'Geelong', lon:144.35, lat:-38.15, cont:'OC', country:'AU'},
  {name_de:'Newcastle', name_en:'Newcastle', lon:151.78, lat:-32.93, cont:'OC', country:'AU'},

  // ── MEXIKO (cont NA, country MX) ──
  {name_de:'Mexiko-Stadt', name_en:'Mexico City', lon:-99.13, lat:19.43, cont:'NA', country:'MX'},
  {name_de:'Guadalajara', name_en:'Guadalajara', lon:-103.35, lat:20.66, cont:'NA', country:'MX'},
  {name_de:'Monterrey', name_en:'Monterrey', lon:-100.32, lat:25.69, cont:'NA', country:'MX'},
  {name_de:'Puebla', name_en:'Puebla', lon:-98.21, lat:19.04, cont:'NA', country:'MX'},
  {name_de:'Tijuana', name_en:'Tijuana', lon:-117.02, lat:32.53, cont:'NA', country:'MX'},
  {name_de:'León', name_en:'León', lon:-101.68, lat:21.12, cont:'NA', country:'MX'},
  {name_de:'Ciudad Juárez', name_en:'Ciudad Juárez', lon:-106.44, lat:31.69, cont:'NA', country:'MX'},
  {name_de:'Mérida', name_en:'Mérida', lon:-89.62, lat:20.97, cont:'NA', country:'MX'},
  {name_de:'Cancún', name_en:'Cancún', lon:-86.85, lat:21.16, cont:'NA', country:'MX'},
  {name_de:'Acapulco', name_en:'Acapulco', lon:-99.88, lat:16.86, cont:'NA', country:'MX'},
  {name_de:'Oaxaca', name_en:'Oaxaca', lon:-96.73, lat:17.06, cont:'NA', country:'MX'},
  {name_de:'Hermosillo', name_en:'Hermosillo', lon:-110.97, lat:29.07, cont:'NA', country:'MX'},
  {name_de:'Veracruz', name_en:'Veracruz', lon:-96.13, lat:19.18, cont:'NA', country:'MX'},
  {name_de:'Chihuahua', name_en:'Chihuahua', lon:-106.09, lat:28.63, cont:'NA', country:'MX'},
  {name_de:'Querétaro', name_en:'Querétaro', lon:-100.39, lat:20.59, cont:'NA', country:'MX'}
];

const PIN_COUNTRY_KEYS=['DE','FR','US','CN','JP','IN','BR','AU','MX'];

const PIN_DECAY={
  DE:120,FR:200,JP:200,
  IN:500,CN:600,BR:700,US:700,AU:700,MX:400,
  EU:500,AF:800,AS:1000,NA:800,SA:800,OC:800,world:1200
};

function getPinCities(region){
  if(!region||region==='world')return PIN_CITIES;
  if(PIN_COUNTRY_KEYS.includes(region))return PIN_CITIES.filter(c=>c.country===region);
  return PIN_CITIES.filter(c=>c.cont===region);
}
