// Weltwährungen für das Währungs-Quiz. Key = ISO-4217-Code (wird als Frage gezeigt),
// {de,en} = Währungsname (wird eingetippt). Länder, die die Währung eines anderen Landes
// nutzen (z.B. Euro-Staaten, USD-Staaten), teilen sich denselben Code — der Pool ist daher
// eine Liste von Währungen, nicht von Ländern.
const CURRENCIES={
AFN:{de:"Afghani",en:"Afghani",es:"Afghani",fr:"Afghani"},
ALL:{de:"Lek",en:"Lek",es:"Lek",fr:"Lek"},
DZD:{de:"Algerischer Dinar",en:"Algerian Dinar",es:"Dinar argelino",fr:"Dinar algérien"},
AOA:{de:"Kwanza",en:"Kwanza",es:"Kwanza",fr:"Kwanza"},
ARS:{de:"Argentinischer Peso",en:"Argentine Peso",es:"Peso argentino",fr:"Peso argentin"},
AMD:{de:"Armenischer Dram",en:"Armenian Dram",es:"Dram armenio",fr:"Dram arménien"},
AUD:{de:"Australischer Dollar",en:"Australian Dollar",es:"Dólar australiano",fr:"Dollar australien"},
AZN:{de:"Aserbaidschan-Manat",en:"Azerbaijani Manat",es:"Manat azerbaiyano",fr:"Manat azerbaïdjanais"},
BSD:{de:"Bahama-Dollar",en:"Bahamian Dollar",es:"Dólar bahameño",fr:"Dollar bahaméen"},
BHD:{de:"Bahrain-Dinar",en:"Bahraini Dinar",es:"Dinar baréini",fr:"Dinar bahreïni"},
BDT:{de:"Taka",en:"Taka",es:"Taka",fr:"Taka"},
BBD:{de:"Barbados-Dollar",en:"Barbadian Dollar",es:"Dólar de Barbados",fr:"Dollar barbadien"},
BYN:{de:"Weißrussischer Rubel",en:"Belarusian Ruble",es:"Rublo bielorruso",fr:"Rouble biélorusse"},
BZD:{de:"Belize-Dollar",en:"Belize Dollar",es:"Dólar beliceño",fr:"Dollar bélizien"},
XOF:{de:"CFA-Franc (Westafrika)",en:"West African CFA Franc",es:"Franco CFA (África Occidental)",fr:"Franc CFA (Afrique de l’Ouest)"},
BTN:{de:"Ngultrum",en:"Ngultrum",es:"Ngultrum",fr:"Ngultrum"},
BOB:{de:"Boliviano",en:"Boliviano",es:"Boliviano",fr:"Boliviano"},
BAM:{de:"Konvertible Mark",en:"Convertible Mark",es:"Marco convertible",fr:"Mark convertible"},
BWP:{de:"Pula",en:"Pula",es:"Pula",fr:"Pula"},
BRL:{de:"Brasilianischer Real",en:"Brazilian Real",es:"Real brasileño",fr:"Real brésilien"},
BND:{de:"Brunei-Dollar",en:"Brunei Dollar",es:"Dólar de Brunéi",fr:"Dollar brunéien"},
BGN:{de:"Bulgarischer Lew",en:"Bulgarian Lev",es:"Lev búlgaro",fr:"Lev bulgare"},
BIF:{de:"Burundi-Franc",en:"Burundian Franc",es:"Franco de Burundi",fr:"Franc burundais"},
KHR:{de:"Riel",en:"Riel",es:"Riel",fr:"Riel"},
XAF:{de:"CFA-Franc (Zentralafrika)",en:"Central African CFA Franc",es:"Franco CFA (África Central)",fr:"Franc CFA (Afrique centrale)"},
CAD:{de:"Kanadischer Dollar",en:"Canadian Dollar",es:"Dólar canadiense",fr:"Dollar canadien"},
CVE:{de:"Kap-Verde-Escudo",en:"Cape Verdean Escudo",es:"Escudo caboverdiano",fr:"Escudo cap-verdien"},
CLP:{de:"Chilenischer Peso",en:"Chilean Peso",es:"Peso chileno",fr:"Peso chilien"},
CNY:{de:"Renminbi Yuan",en:"Chinese Yuan",es:"Yuan renminbi",fr:"Yuan renminbi"},
COP:{de:"Kolumbianischer Peso",en:"Colombian Peso",es:"Peso colombiano",fr:"Peso colombien"},
KMF:{de:"Komoren-Franc",en:"Comorian Franc",es:"Franco comorano",fr:"Franc comorien"},
CDF:{de:"Kongo-Franc",en:"Congolese Franc",es:"Franco congoleño",fr:"Franc congolais"},
CRC:{de:"Costa-Rica-Colón",en:"Costa Rican Colon",es:"Colón costarricense",fr:"Colón costaricain"},
CUP:{de:"Kubanischer Peso",en:"Cuban Peso",es:"Peso cubano",fr:"Peso cubain"},
CZK:{de:"Tschechische Krone",en:"Czech Koruna",es:"Corona checa",fr:"Couronne tchèque"},
DKK:{de:"Dänische Krone",en:"Danish Krone",es:"Corona danesa",fr:"Couronne danoise"},
DJF:{de:"Dschibuti-Franc",en:"Djiboutian Franc",es:"Franco yibutiano",fr:"Franc djiboutien"},
DOP:{de:"Dominikanischer Peso",en:"Dominican Peso",es:"Peso dominicano",fr:"Peso dominicain"},
EGP:{de:"Ägyptisches Pfund",en:"Egyptian Pound",es:"Libra egipcia",fr:"Livre égyptienne"},
ERN:{de:"Nakfa",en:"Nakfa",es:"Nakfa",fr:"Nakfa"},
SZL:{de:"Lilangeni",en:"Lilangeni",es:"Lilangeni",fr:"Lilangeni"},
ETB:{de:"Birr",en:"Ethiopian Birr",es:"Birr etíope",fr:"Birr éthiopien"},
EUR:{de:"Euro",en:"Euro",es:"Euro",fr:"Euro"},
FJD:{de:"Fidschi-Dollar",en:"Fijian Dollar",es:"Dólar fiyiano",fr:"Dollar fidjien"},
GMD:{de:"Dalasi",en:"Dalasi",es:"Dalasi",fr:"Dalasi"},
GEL:{de:"Georgischer Lari",en:"Georgian Lari",es:"Lari georgiano",fr:"Lari géorgien"},
GHS:{de:"Ghanaischer Cedi",en:"Ghanaian Cedi",es:"Cedi ganés",fr:"Cedi ghanéen"},
GTQ:{de:"Quetzal",en:"Quetzal",es:"Quetzal",fr:"Quetzal"},
GNF:{de:"Guinea-Franc",en:"Guinean Franc",es:"Franco guineano",fr:"Franc guinéen"},
GYD:{de:"Guyana-Dollar",en:"Guyanese Dollar",es:"Dólar guyanés",fr:"Dollar guyanien"},
HTG:{de:"Gourde",en:"Gourde",es:"Gourde",fr:"Gourde"},
HNL:{de:"Lempira",en:"Lempira",es:"Lempira",fr:"Lempira"},
HKD:{de:"Hongkong-Dollar",en:"Hong Kong Dollar",es:"Dólar de Hong Kong",fr:"Dollar de Hong Kong"},
HUF:{de:"Forint",en:"Forint",es:"Forinto",fr:"Forint"},
ISK:{de:"Isländische Krone",en:"Icelandic Krona",es:"Corona islandesa",fr:"Couronne islandaise"},
INR:{de:"Indische Rupie",en:"Indian Rupee",es:"Rupia india",fr:"Roupie indienne"},
IDR:{de:"Indonesische Rupiah",en:"Indonesian Rupiah",es:"Rupia indonesia",fr:"Roupie indonésienne"},
IRR:{de:"Iranischer Rial",en:"Iranian Rial",es:"Rial iraní",fr:"Rial iranien"},
IQD:{de:"Irakischer Dinar",en:"Iraqi Dinar",es:"Dinar iraquí",fr:"Dinar irakien"},
ILS:{de:"Schekel",en:"Israeli Shekel",es:"Séquel israelí",fr:"Shekel israélien"},
JMD:{de:"Jamaika-Dollar",en:"Jamaican Dollar",es:"Dólar jamaicano",fr:"Dollar jamaïcain"},
JPY:{de:"Yen",en:"Japanese Yen",es:"Yen",fr:"Yen"},
JOD:{de:"Jordanischer Dinar",en:"Jordanian Dinar",es:"Dinar jordano",fr:"Dinar jordanien"},
KZT:{de:"Tenge",en:"Kazakhstani Tenge",es:"Tenge kazajo",fr:"Tenge kazakh"},
KES:{de:"Kenia-Schilling",en:"Kenyan Shilling",es:"Chelín keniano",fr:"Shilling kényan"},
KPW:{de:"Nordkoreanischer Won",en:"North Korean Won",es:"Won norcoreano",fr:"Won nord-coréen"},
KRW:{de:"Südkoreanischer Won",en:"South Korean Won",es:"Won surcoreano",fr:"Won sud-coréen"},
KWD:{de:"Kuwait-Dinar",en:"Kuwaiti Dinar",es:"Dinar kuwaití",fr:"Dinar koweïtien"},
KGS:{de:"Som (Kirgisistan)",en:"Kyrgyzstani Som",es:"Som kirguís",fr:"Som kirghize"},
LAK:{de:"Kip",en:"Lao Kip",es:"Kip laosiano",fr:"Kip laotien"},
LBP:{de:"Libanesisches Pfund",en:"Lebanese Pound",es:"Libra libanesa",fr:"Livre libanaise"},
LSL:{de:"Loti",en:"Lesotho Loti",es:"Loti",fr:"Loti"},
LRD:{de:"Liberianischer Dollar",en:"Liberian Dollar",es:"Dólar liberiano",fr:"Dollar libérien"},
LYD:{de:"Libyscher Dinar",en:"Libyan Dinar",es:"Dinar libio",fr:"Dinar libyen"},
CHF:{de:"Schweizer Franken",en:"Swiss Franc",es:"Franco suizo",fr:"Franc suisse"},
MOP:{de:"Pataca",en:"Macanese Pataca",es:"Pataca",fr:"Pataca"},
MKD:{de:"Denar",en:"Macedonian Denar",es:"Denar macedonio",fr:"Denar macédonien"},
MGA:{de:"Ariary",en:"Malagasy Ariary",es:"Ariary malgache",fr:"Ariary malgache"},
MWK:{de:"Malawi-Kwacha",en:"Malawian Kwacha",es:"Kwacha malaui",fr:"Kwacha malawite"},
MYR:{de:"Ringgit",en:"Malaysian Ringgit",es:"Ringgit malayo",fr:"Ringgit malaisien"},
MVR:{de:"Rufiyaa",en:"Maldivian Rufiyaa",es:"Rufiyaa",fr:"Rufiyaa"},
MRU:{de:"Ouguiya",en:"Mauritanian Ouguiya",es:"Uguiya",fr:"Ouguiya"},
MUR:{de:"Mauritius-Rupie",en:"Mauritian Rupee",es:"Rupia mauriciana",fr:"Roupie mauricienne"},
MXN:{de:"Mexikanischer Peso",en:"Mexican Peso",es:"Peso mexicano",fr:"Peso mexicain"},
MDL:{de:"Moldau-Leu",en:"Moldovan Leu",es:"Leu moldavo",fr:"Leu moldave"},
MNT:{de:"Tögrög",en:"Mongolian Togrog",es:"Tugrik",fr:"Tugrik"},
MAD:{de:"Marokkanischer Dirham",en:"Moroccan Dirham",es:"Dírham marroquí",fr:"Dirham marocain"},
MZN:{de:"Mosambik-Metical",en:"Mozambican Metical",es:"Metical mozambiqueño",fr:"Metical mozambicain"},
MMK:{de:"Kyat",en:"Myanmar Kyat",es:"Kyat",fr:"Kyat"},
NAD:{de:"Namibia-Dollar",en:"Namibian Dollar",es:"Dólar namibio",fr:"Dollar namibien"},
NPR:{de:"Nepalesische Rupie",en:"Nepalese Rupee",es:"Rupia nepalí",fr:"Roupie népalaise"},
NZD:{de:"Neuseeland-Dollar",en:"New Zealand Dollar",es:"Dólar neozelandés",fr:"Dollar néo-zélandais"},
NIO:{de:"Córdoba",en:"Nicaraguan Cordoba",es:"Córdoba",fr:"Córdoba"},
NGN:{de:"Naira",en:"Nigerian Naira",es:"Naira",fr:"Naira"},
NOK:{de:"Norwegische Krone",en:"Norwegian Krone",es:"Corona noruega",fr:"Couronne norvégienne"},
OMR:{de:"Omanischer Rial",en:"Omani Rial",es:"Rial omaní",fr:"Rial omanais"},
PKR:{de:"Pakistanische Rupie",en:"Pakistani Rupee",es:"Rupia pakistaní",fr:"Roupie pakistanaise"},
PAB:{de:"Balboa",en:"Panamanian Balboa",es:"Balboa",fr:"Balboa"},
PGK:{de:"Kina",en:"Papua-Neuguinea-Kina",es:"Kina",fr:"Kina"},
PYG:{de:"Guaraní",en:"Paraguayan Guarani",es:"Guaraní",fr:"Guarani"},
PEN:{de:"Sol",en:"Peruvian Sol",es:"Sol",fr:"Sol péruvien"},
PHP:{de:"Philippinischer Peso",en:"Philippine Peso",es:"Peso filipino",fr:"Peso philippin"},
PLN:{de:"Złoty",en:"Polish Zloty",es:"Zloty",fr:"Złoty"},
QAR:{de:"Katar-Riyal",en:"Qatari Riyal",es:"Riyal catarí",fr:"Riyal qatari"},
RON:{de:"Rumänischer Leu",en:"Romanian Leu",es:"Leu rumano",fr:"Leu roumain"},
RUB:{de:"Russischer Rubel",en:"Russian Ruble",es:"Rublo ruso",fr:"Rouble russe"},
RWF:{de:"Ruanda-Franc",en:"Rwandan Franc",es:"Franco ruandés",fr:"Franc rwandais"},
WST:{de:"Tala",en:"Samoan Tala",es:"Tala",fr:"Tala"},
STN:{de:"Dobra",en:"São Tomé and Príncipe Dobra",es:"Dobra",fr:"Dobra"},
SAR:{de:"Saudi-Riyal",en:"Saudi Riyal",es:"Riyal saudí",fr:"Riyal saoudien"},
RSD:{de:"Serbischer Dinar",en:"Serbian Dinar",es:"Dinar serbio",fr:"Dinar serbe"},
SCR:{de:"Seychellen-Rupie",en:"Seychellois Rupee",es:"Rupia seychellense",fr:"Roupie seychelloise"},
SLE:{de:"Leone",en:"Sierra Leonean Leone",es:"Leone",fr:"Leone"},
SGD:{de:"Singapur-Dollar",en:"Singapore Dollar",es:"Dólar de Singapur",fr:"Dollar de Singapour"},
SBD:{de:"Salomonen-Dollar",en:"Solomon Islands Dollar",es:"Dólar de las Salomón",fr:"Dollar des Salomon"},
SOS:{de:"Somalia-Schilling",en:"Somali Shilling",es:"Chelín somalí",fr:"Shilling somalien"},
ZAR:{de:"Südafrikanischer Rand",en:"South African Rand",es:"Rand sudafricano",fr:"Rand sud-africain"},
SSP:{de:"Südsudanesisches Pfund",en:"South Sudanese Pound",es:"Libra sursudanesa",fr:"Livre sud-soudanaise"},
LKR:{de:"Sri-Lanka-Rupie",en:"Sri Lankan Rupee",es:"Rupia esrilanquesa",fr:"Roupie srilankaise"},
SDG:{de:"Sudanesisches Pfund",en:"Sudanese Pound",es:"Libra sudanesa",fr:"Livre soudanaise"},
SRD:{de:"Suriname-Dollar",en:"Surinamese Dollar",es:"Dólar surinamés",fr:"Dollar surinamais"},
SEK:{de:"Schwedische Krone",en:"Swedish Krona",es:"Corona sueca",fr:"Couronne suédoise"},
SYP:{de:"Syrisches Pfund",en:"Syrian Pound",es:"Libra siria",fr:"Livre syrienne"},
TWD:{de:"Taiwan-Dollar",en:"New Taiwan Dollar",es:"Nuevo dólar taiwanés",fr:"Nouveau dollar taïwanais"},
TJS:{de:"Somoni",en:"Tajikistani Somoni",es:"Somoni",fr:"Somoni"},
TZS:{de:"Tansania-Schilling",en:"Tanzanian Shilling",es:"Chelín tanzano",fr:"Shilling tanzanien"},
THB:{de:"Baht",en:"Thai Baht",es:"Baht",fr:"Baht"},
TOP:{de:"Pa'anga",en:"Tongan Pa'anga",es:"Pa'anga",fr:"Pa'anga"},
TTD:{de:"Trinidad-und-Tobago-Dollar",en:"Trinidad and Tobago Dollar",es:"Dólar de Trinidad y Tobago",fr:"Dollar de Trinité-et-Tobago"},
TND:{de:"Tunesischer Dinar",en:"Tunisian Dinar",es:"Dinar tunecino",fr:"Dinar tunisien"},
TRY:{de:"Türkische Lira",en:"Turkish Lira",es:"Lira turca",fr:"Livre turque"},
TMT:{de:"Turkmenistan-Manat",en:"Turkmenistani Manat",es:"Manat turcomano",fr:"Manat turkmène"},
UGX:{de:"Uganda-Schilling",en:"Ugandan Shilling",es:"Chelín ugandés",fr:"Shilling ougandais"},
UAH:{de:"Hrywnja",en:"Ukrainian Hryvnia",es:"Grivna",fr:"Hryvnia"},
AED:{de:"VAE-Dirham",en:"UAE Dirham",es:"Dírham de los EAU",fr:"Dirham des ÉAU"},
GBP:{de:"Britisches Pfund",en:"British Pound",es:"Libra esterlina",fr:"Livre sterling"},
USD:{de:"US-Dollar",en:"US Dollar",es:"Dólar estadounidense",fr:"Dollar américain"},
UYU:{de:"Uruguayischer Peso",en:"Uruguayan Peso",es:"Peso uruguayo",fr:"Peso uruguayen"},
UZS:{de:"Usbekistan-Sum",en:"Uzbekistani Som",es:"Som uzbeko",fr:"Sum ouzbek"},
VUV:{de:"Vatu",en:"Vanuatu Vatu",es:"Vatu",fr:"Vatu"},
VES:{de:"Bolívar Soberano",en:"Venezuelan Bolivar",es:"Bolívar soberano",fr:"Bolívar souverain"},
VND:{de:"Dong",en:"Vietnamese Dong",es:"Dong",fr:"Dong"},
YER:{de:"Jemen-Rial",en:"Yemeni Rial",es:"Rial yemení",fr:"Rial yéménite"},
ZMW:{de:"Sambia-Kwacha",en:"Zambian Kwacha",es:"Kwacha zambiano",fr:"Kwacha zambien"},
XCD:{de:"Ostkaribischer Dollar",en:"East Caribbean Dollar",es:"Dólar del Caribe Oriental",fr:"Dollar des Caraïbes orientales"}
};
