// Weltwährungen für das Währungs-Quiz. Key = ISO-4217-Code (wird als Frage gezeigt),
// {de,en} = Währungsname (wird eingetippt). Länder, die die Währung eines anderen Landes
// nutzen (z.B. Euro-Staaten, USD-Staaten), teilen sich denselben Code — der Pool ist daher
// eine Liste von Währungen, nicht von Ländern.
const CURRENCIES={
AFN:{de:'Afghani',en:'Afghani'},ALL:{de:'Lek',en:'Lek'},DZD:{de:'Algerischer Dinar',en:'Algerian Dinar'},
AOA:{de:'Kwanza',en:'Kwanza'},ARS:{de:'Argentinischer Peso',en:'Argentine Peso'},AMD:{de:'Armenischer Dram',en:'Armenian Dram'},
AUD:{de:'Australischer Dollar',en:'Australian Dollar'},AZN:{de:'Aserbaidschan-Manat',en:'Azerbaijani Manat'},
BSD:{de:'Bahama-Dollar',en:'Bahamian Dollar'},BHD:{de:'Bahrain-Dinar',en:'Bahraini Dinar'},BDT:{de:'Taka',en:'Taka'},
BBD:{de:'Barbados-Dollar',en:'Barbadian Dollar'},BYN:{de:'Weißrussischer Rubel',en:'Belarusian Ruble'},
BZD:{de:'Belize-Dollar',en:'Belize Dollar'},XOF:{de:'CFA-Franc (Westafrika)',en:'West African CFA Franc'},
BTN:{de:'Ngultrum',en:'Ngultrum'},BOB:{de:'Boliviano',en:'Boliviano'},BAM:{de:'Konvertible Mark',en:'Convertible Mark'},
BWP:{de:'Pula',en:'Pula'},BRL:{de:'Brasilianischer Real',en:'Brazilian Real'},BND:{de:'Brunei-Dollar',en:'Brunei Dollar'},
BGN:{de:'Bulgarischer Lew',en:'Bulgarian Lev'},BIF:{de:'Burundi-Franc',en:'Burundian Franc'},KHR:{de:'Riel',en:'Riel'},
XAF:{de:'CFA-Franc (Zentralafrika)',en:'Central African CFA Franc'},CAD:{de:'Kanadischer Dollar',en:'Canadian Dollar'},
CVE:{de:'Kap-Verde-Escudo',en:'Cape Verdean Escudo'},CLP:{de:'Chilenischer Peso',en:'Chilean Peso'},
CNY:{de:'Renminbi Yuan',en:'Chinese Yuan'},COP:{de:'Kolumbianischer Peso',en:'Colombian Peso'},
KMF:{de:'Komoren-Franc',en:'Comorian Franc'},CDF:{de:'Kongo-Franc',en:'Congolese Franc'},
CRC:{de:'Costa-Rica-Colón',en:'Costa Rican Colon'},CUP:{de:'Kubanischer Peso',en:'Cuban Peso'},
CZK:{de:'Tschechische Krone',en:'Czech Koruna'},DKK:{de:'Dänische Krone',en:'Danish Krone'},
DJF:{de:'Dschibuti-Franc',en:'Djiboutian Franc'},DOP:{de:'Dominikanischer Peso',en:'Dominican Peso'},
EGP:{de:'Ägyptisches Pfund',en:'Egyptian Pound'},ERN:{de:'Nakfa',en:'Nakfa'},SZL:{de:'Lilangeni',en:'Lilangeni'},
ETB:{de:'Birr',en:'Ethiopian Birr'},EUR:{de:'Euro',en:'Euro'},FJD:{de:'Fidschi-Dollar',en:'Fijian Dollar'},
GMD:{de:'Dalasi',en:'Dalasi'},GEL:{de:'Georgischer Lari',en:'Georgian Lari'},GHS:{de:'Ghanaischer Cedi',en:'Ghanaian Cedi'},
GTQ:{de:'Quetzal',en:'Quetzal'},GNF:{de:'Guinea-Franc',en:'Guinean Franc'},GYD:{de:'Guyana-Dollar',en:'Guyanese Dollar'},
HTG:{de:'Gourde',en:'Gourde'},HNL:{de:'Lempira',en:'Lempira'},HKD:{de:'Hongkong-Dollar',en:'Hong Kong Dollar'},
HUF:{de:'Forint',en:'Forint'},ISK:{de:'Isländische Krone',en:'Icelandic Krona'},INR:{de:'Indische Rupie',en:'Indian Rupee'},
IDR:{de:'Indonesische Rupiah',en:'Indonesian Rupiah'},IRR:{de:'Iranischer Rial',en:'Iranian Rial'},
IQD:{de:'Irakischer Dinar',en:'Iraqi Dinar'},ILS:{de:'Schekel',en:'Israeli Shekel'},JMD:{de:'Jamaika-Dollar',en:'Jamaican Dollar'},
JPY:{de:'Yen',en:'Japanese Yen'},JOD:{de:'Jordanischer Dinar',en:'Jordanian Dinar'},KZT:{de:'Tenge',en:'Kazakhstani Tenge'},
KES:{de:'Kenia-Schilling',en:'Kenyan Shilling'},KPW:{de:'Nordkoreanischer Won',en:'North Korean Won'},
KRW:{de:'Südkoreanischer Won',en:'South Korean Won'},KWD:{de:'Kuwait-Dinar',en:'Kuwaiti Dinar'},
KGS:{de:'Som (Kirgisistan)',en:'Kyrgyzstani Som'},LAK:{de:'Kip',en:'Lao Kip'},LBP:{de:'Libanesisches Pfund',en:'Lebanese Pound'},
LSL:{de:'Loti',en:'Lesotho Loti'},LRD:{de:'Liberianischer Dollar',en:'Liberian Dollar'},
LYD:{de:'Libyscher Dinar',en:'Libyan Dinar'},CHF:{de:'Schweizer Franken',en:'Swiss Franc'},MOP:{de:'Pataca',en:'Macanese Pataca'},
MKD:{de:'Denar',en:'Macedonian Denar'},MGA:{de:'Ariary',en:'Malagasy Ariary'},MWK:{de:'Malawi-Kwacha',en:'Malawian Kwacha'},
MYR:{de:'Ringgit',en:'Malaysian Ringgit'},MVR:{de:'Rufiyaa',en:'Maldivian Rufiyaa'},MRU:{de:'Ouguiya',en:'Mauritanian Ouguiya'},
MUR:{de:'Mauritius-Rupie',en:'Mauritian Rupee'},MXN:{de:'Mexikanischer Peso',en:'Mexican Peso'},
MDL:{de:'Moldau-Leu',en:'Moldovan Leu'},MNT:{de:'Tögrög',en:'Mongolian Togrog'},MAD:{de:'Marokkanischer Dirham',en:'Moroccan Dirham'},
MZN:{de:'Mosambik-Metical',en:'Mozambican Metical'},MMK:{de:'Kyat',en:'Myanmar Kyat'},NAD:{de:'Namibia-Dollar',en:'Namibian Dollar'},
NPR:{de:'Nepalesische Rupie',en:'Nepalese Rupee'},NZD:{de:'Neuseeland-Dollar',en:'New Zealand Dollar'},
NIO:{de:'Córdoba',en:'Nicaraguan Cordoba'},NGN:{de:'Naira',en:'Nigerian Naira'},NOK:{de:'Norwegische Krone',en:'Norwegian Krone'},
OMR:{de:'Omanischer Rial',en:'Omani Rial'},PKR:{de:'Pakistanische Rupie',en:'Pakistani Rupee'},PAB:{de:'Balboa',en:'Panamanian Balboa'},
PGK:{de:'Kina',en:'Papua-Neuguinea-Kina'},PYG:{de:'Guaraní',en:'Paraguayan Guarani'},PEN:{de:'Sol',en:'Peruvian Sol'},
PHP:{de:'Philippinischer Peso',en:'Philippine Peso'},PLN:{de:'Złoty',en:'Polish Zloty'},QAR:{de:'Katar-Riyal',en:'Qatari Riyal'},
RON:{de:'Rumänischer Leu',en:'Romanian Leu'},RUB:{de:'Russischer Rubel',en:'Russian Ruble'},RWF:{de:'Ruanda-Franc',en:'Rwandan Franc'},
WST:{de:'Tala',en:'Samoan Tala'},STN:{de:'Dobra',en:'São Tomé and Príncipe Dobra'},SAR:{de:'Saudi-Riyal',en:'Saudi Riyal'},
RSD:{de:'Serbischer Dinar',en:'Serbian Dinar'},SCR:{de:'Seychellen-Rupie',en:'Seychellois Rupee'},SLE:{de:'Leone',en:'Sierra Leonean Leone'},
SGD:{de:'Singapur-Dollar',en:'Singapore Dollar'},SBD:{de:'Salomonen-Dollar',en:'Solomon Islands Dollar'},
SOS:{de:'Somalia-Schilling',en:'Somali Shilling'},ZAR:{de:'Südafrikanischer Rand',en:'South African Rand'},
SSP:{de:'Südsudanesisches Pfund',en:'South Sudanese Pound'},LKR:{de:'Sri-Lanka-Rupie',en:'Sri Lankan Rupee'},
SDG:{de:'Sudanesisches Pfund',en:'Sudanese Pound'},SRD:{de:'Suriname-Dollar',en:'Surinamese Dollar'},
SEK:{de:'Schwedische Krone',en:'Swedish Krona'},SYP:{de:'Syrisches Pfund',en:'Syrian Pound'},TWD:{de:'Taiwan-Dollar',en:'New Taiwan Dollar'},
TJS:{de:'Somoni',en:'Tajikistani Somoni'},TZS:{de:'Tansania-Schilling',en:'Tanzanian Shilling'},THB:{de:'Baht',en:'Thai Baht'},
TOP:{de:"Pa'anga",en:"Tongan Pa'anga"},TTD:{de:'Trinidad-und-Tobago-Dollar',en:'Trinidad and Tobago Dollar'},
TND:{de:'Tunesischer Dinar',en:'Tunisian Dinar'},TRY:{de:'Türkische Lira',en:'Turkish Lira'},
TMT:{de:'Turkmenistan-Manat',en:'Turkmenistani Manat'},UGX:{de:'Uganda-Schilling',en:'Ugandan Shilling'},
UAH:{de:'Hrywnja',en:'Ukrainian Hryvnia'},AED:{de:'VAE-Dirham',en:'UAE Dirham'},GBP:{de:'Britisches Pfund',en:'British Pound'},
USD:{de:'US-Dollar',en:'US Dollar'},UYU:{de:'Uruguayischer Peso',en:'Uruguayan Peso'},UZS:{de:'Usbekistan-Sum',en:'Uzbekistani Som'},
VUV:{de:'Vatu',en:'Vanuatu Vatu'},VES:{de:'Bolívar Soberano',en:'Venezuelan Bolivar'},VND:{de:'Dong',en:'Vietnamese Dong'},
YER:{de:'Jemen-Rial',en:'Yemeni Rial'},ZMW:{de:'Sambia-Kwacha',en:'Zambian Kwacha'},XCD:{de:'Ostkaribischer Dollar',en:'East Caribbean Dollar'}
};
