// Sprachen für das Sprachen-Quiz. Key = interner Sprachcode, {de,en} = Sprachname (wird
// eingetippt), ex = kurzer Beispielsatz IN dieser Sprache (wird als Frage gezeigt). Der Satz
// bedeutet überall sinngemäß "Mein Name ist Leander" — ein Name macht den Satz auch ohne
// Sprachkenntnis klar lesbar, egal ob im lateinischen oder einem anderen Schriftsystem.
const LANGUAGES={
de:{de:'Deutsch',en:'German',ex:'Ich heiße Leander.'},
en:{de:'Englisch',en:'English',ex:'My name is Leander.'},
fr:{de:'Französisch',en:'French',ex:"Je m'appelle Leander."},
es:{de:'Spanisch',en:'Spanish',ex:'Me llamo Leander.'},
it:{de:'Italienisch',en:'Italian',ex:'Mi chiamo Leander.'},
pt:{de:'Portugiesisch',en:'Portuguese',ex:'O meu nome é Leander.'},
nl:{de:'Niederländisch',en:'Dutch',ex:'Ik heet Leander.'},
sv:{de:'Schwedisch',en:'Swedish',ex:'Jag heter Leander.'},
no:{de:'Norwegisch',en:'Norwegian',ex:'Jeg heter Leander.'},
da:{de:'Dänisch',en:'Danish',ex:'Jeg hedder Leander.'},
fi:{de:'Finnisch',en:'Finnish',ex:'Nimeni on Leander.'},
is:{de:'Isländisch',en:'Icelandic',ex:'Ég heiti Leander.'},
pl:{de:'Polnisch',en:'Polish',ex:'Mam na imię Leander.'},
cs:{de:'Tschechisch',en:'Czech',ex:'Jmenuji se Leander.'},
sk:{de:'Slowakisch',en:'Slovak',ex:'Volám sa Leander.'},
hu:{de:'Ungarisch',en:'Hungarian',ex:'A nevem Leander.'},
ro:{de:'Rumänisch',en:'Romanian',ex:'Mă numesc Leander.'},
bg:{de:'Bulgarisch',en:'Bulgarian',ex:'Казвам се Leander.'},
el:{de:'Griechisch',en:'Greek',ex:'Με λένε Leander.'},
ru:{de:'Russisch',en:'Russian',ex:'Меня зовут Leander.'},
uk:{de:'Ukrainisch',en:'Ukrainian',ex:'Мене звати Leander.'},
tr:{de:'Türkisch',en:'Turkish',ex:'Benim adım Leander.'},
ar:{de:'Arabisch',en:'Arabic',ex:'اسمي ليأندر.'},
he:{de:'Hebräisch',en:'Hebrew',ex:'קוראים לי לياندר.'},
hi:{de:'Hindi',en:'Hindi',ex:'मेरा नाम लीएंडर है।'},
bn:{de:'Bengalisch',en:'Bengali',ex:'আমার নাম লিয়েন্ডার।'},
fa:{de:'Persisch',en:'Persian',ex:'اسم من لیاندر است.'},
ur:{de:'Urdu',en:'Urdu',ex:'میرا نام لیانڈر ہے۔'},
zh:{de:'Chinesisch',en:'Chinese',ex:'我叫Leander。'},
ja:{de:'Japanisch',en:'Japanese',ex:'私の名前はレアンダーです。'},
ko:{de:'Koreanisch',en:'Korean',ex:'제 이름은 레안더입니다.'},
vi:{de:'Vietnamesisch',en:'Vietnamese',ex:'Tôi tên là Leander.'},
th:{de:'Thailändisch',en:'Thai',ex:'ผมชื่อลีแอนเดอร์'},
id:{de:'Indonesisch',en:'Indonesian',ex:'Nama saya Leander.'},
tl:{de:'Filipino',en:'Filipino',ex:'Ang pangalan ko ay Leander.'},
sw:{de:'Suaheli',en:'Swahili',ex:'Jina langu ni Leander.'},
af:{de:'Afrikaans',en:'Afrikaans',ex:'My naam is Leander.'},
hr:{de:'Kroatisch',en:'Croatian',ex:'Zovem se Leander.'},
et:{de:'Estnisch',en:'Estonian',ex:'Minu nimi on Leander.'},
lv:{de:'Lettisch',en:'Latvian',ex:'Mani sauc Leander.'},
lt:{de:'Litauisch',en:'Lithuanian',ex:'Mano vardas Leander.'},
sq:{de:'Albanisch',en:'Albanian',ex:'Unë quhem Leander.'}
};
