// Sprachen für das Sprachen-Quiz. Key = interner Sprachcode, {de,en} = Sprachname (wird
// eingetippt), ex = kurzer Beispielsatz IN dieser Sprache (wird als Frage gezeigt). Der Satz
// bedeutet überall sinngemäß "Mein Name ist Leander" — ein Name macht den Satz auch ohne
// Sprachkenntnis klar lesbar, egal ob im lateinischen oder einem anderen Schriftsystem.
const LANGUAGES={
de:{de:"Deutsch",en:"German",es:"Alemán",fr:"Allemand",ex:"Ich heiße Leander."},
en:{de:"Englisch",en:"English",es:"Inglés",fr:"Anglais",ex:"My name is Leander."},
fr:{de:"Französisch",en:"French",es:"Francés",fr:"Français",ex:"Je m'appelle Leander."},
es:{de:"Spanisch",en:"Spanish",es:"Español",fr:"Espagnol",ex:"Me llamo Leander."},
it:{de:"Italienisch",en:"Italian",es:"Italiano",fr:"Italien",ex:"Mi chiamo Leander."},
pt:{de:"Portugiesisch",en:"Portuguese",es:"Portugués",fr:"Portugais",ex:"O meu nome é Leander."},
nl:{de:"Niederländisch",en:"Dutch",es:"Neerlandés",fr:"Néerlandais",ex:"Ik heet Leander."},
sv:{de:"Schwedisch",en:"Swedish",es:"Sueco",fr:"Suédois",ex:"Jag heter Leander."},
no:{de:"Norwegisch",en:"Norwegian",es:"Noruego",fr:"Norvégien",ex:"Jeg heter Leander."},
da:{de:"Dänisch",en:"Danish",es:"Danés",fr:"Danois",ex:"Jeg hedder Leander."},
fi:{de:"Finnisch",en:"Finnish",es:"Finlandés",fr:"Finnois",ex:"Nimeni on Leander."},
is:{de:"Isländisch",en:"Icelandic",es:"Islandés",fr:"Islandais",ex:"Ég heiti Leander."},
pl:{de:"Polnisch",en:"Polish",es:"Polaco",fr:"Polonais",ex:"Mam na imię Leander."},
cs:{de:"Tschechisch",en:"Czech",es:"Checo",fr:"Tchèque",ex:"Jmenuji se Leander."},
sk:{de:"Slowakisch",en:"Slovak",es:"Eslovaco",fr:"Slovaque",ex:"Volám sa Leander."},
hu:{de:"Ungarisch",en:"Hungarian",es:"Húngaro",fr:"Hongrois",ex:"A nevem Leander."},
ro:{de:"Rumänisch",en:"Romanian",es:"Rumano",fr:"Roumain",ex:"Mă numesc Leander."},
bg:{de:"Bulgarisch",en:"Bulgarian",es:"Búlgaro",fr:"Bulgare",ex:"Казвам се Leander."},
el:{de:"Griechisch",en:"Greek",es:"Griego",fr:"Grec",ex:"Με λένε Leander."},
ru:{de:"Russisch",en:"Russian",es:"Ruso",fr:"Russe",ex:"Меня зовут Leander."},
uk:{de:"Ukrainisch",en:"Ukrainian",es:"Ucraniano",fr:"Ukrainien",ex:"Мене звати Leander."},
tr:{de:"Türkisch",en:"Turkish",es:"Turco",fr:"Turc",ex:"Benim adım Leander."},
ar:{de:"Arabisch",en:"Arabic",es:"Árabe",fr:"Arabe",ex:"اسمي ليأندر."},
he:{de:"Hebräisch",en:"Hebrew",es:"Hebreo",fr:"Hébreu",ex:"קוראים לי לياندר."},
hi:{de:"Hindi",en:"Hindi",es:"Hindi",fr:"Hindi",ex:"मेरा नाम लीएंडर है।"},
bn:{de:"Bengalisch",en:"Bengali",es:"Bengalí",fr:"Bengali",ex:"আমার নাম লিয়েন্ডার।"},
fa:{de:"Persisch",en:"Persian",es:"Persa",fr:"Persan",ex:"اسم من لیاندر است."},
ur:{de:"Urdu",en:"Urdu",es:"Urdu",fr:"Ourdou",ex:"میرا نام لیانڈر ہے۔"},
zh:{de:"Chinesisch",en:"Chinese",es:"Chino",fr:"Chinois",ex:"我叫Leander。"},
ja:{de:"Japanisch",en:"Japanese",es:"Japonés",fr:"Japonais",ex:"私の名前はレアンダーです。"},
ko:{de:"Koreanisch",en:"Korean",es:"Coreano",fr:"Coréen",ex:"제 이름은 레안더입니다."},
vi:{de:"Vietnamesisch",en:"Vietnamese",es:"Vietnamita",fr:"Vietnamien",ex:"Tôi tên là Leander."},
th:{de:"Thailändisch",en:"Thai",es:"Tailandés",fr:"Thaï",ex:"ผมชื่อลีแอนเดอร์"},
id:{de:"Indonesisch",en:"Indonesian",es:"Indonesio",fr:"Indonésien",ex:"Nama saya Leander."},
tl:{de:"Filipino",en:"Filipino",es:"Filipino",fr:"Filipino",ex:"Ang pangalan ko ay Leander."},
sw:{de:"Suaheli",en:"Swahili",es:"Suajili",fr:"Swahili",ex:"Jina langu ni Leander."},
af:{de:"Afrikaans",en:"Afrikaans",es:"Afrikáans",fr:"Afrikaans",ex:"My naam is Leander."},
hr:{de:"Kroatisch",en:"Croatian",es:"Croata",fr:"Croate",ex:"Zovem se Leander."},
et:{de:"Estnisch",en:"Estonian",es:"Estonio",fr:"Estonien",ex:"Minu nimi on Leander."},
lv:{de:"Lettisch",en:"Latvian",es:"Letón",fr:"Letton",ex:"Mani sauc Leander."},
lt:{de:"Litauisch",en:"Lithuanian",es:"Lituano",fr:"Lituanien",ex:"Mano vardas Leander."},
sq:{de:"Albanisch",en:"Albanian",es:"Albanés",fr:"Albanais",ex:"Unë quhem Leander."}
};
